INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_kttv_q1', 'Câu 01: Thế nào là nhật triều?', 'gk2_kttv', 1);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q1_a1', 'Là hiện tượng xảy ra trong một ngày đêm trăng (24h50’) có 1 lần triều lên và 1 lần triều xuống.', 'gk2_kttv_q1');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q1_a2', 'Là hiện tượng xảy ra trong một ngày đêm trăng (24h50’) có 2 lần triều lên và 2 lần triều xuống.', 'gk2_kttv_q1');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q1_a3', 'Là hiện tượng xảy ra trong một ngày đêm trăng (24h50’) có 1 lần triều lên và 2 lần triều xuống.', 'gk2_kttv_q1');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q1_a4', 'Là hiện tượng xảy ra trong một ngày đêm trăng (24h50’) có 2 lần triều lên và 1 lần triều xuống.', 'gk2_kttv_q1');
UPDATE questions SET correct_answer_id = 'gk2_kttv_q1_a1' WHERE id = 'gk2_kttv_q1';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_kttv_q2', 'Câu 02: Thế nào là bán nhật triều?', 'gk2_kttv', 2);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q2_a1', 'Là hiện tượng xảy ra trong một ngày đêm trăng (24h50’) có 1 lần triều lên và 1 lần triều xuống.', 'gk2_kttv_q2');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q2_a2', 'Là hiện tượng xảy ra trong một ngày đêm trăng(24h50’) có 2 lần triều lên và 2 lần triều xuống.', 'gk2_kttv_q2');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q2_a3', 'Là hiện tượng xảy ra trong một ngày đêm trăng (24h50’) có 1 lần triều lên và 2 lần triều xuống.', 'gk2_kttv_q2');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q2_a4', 'Là hiện tượng xảy ra trong một ngày đêm trăng (24h50’) có 2 lần triều lên và 1 lần triều xuống.', 'gk2_kttv_q2');
UPDATE questions SET correct_answer_id = 'gk2_kttv_q2_a2' WHERE id = 'gk2_kttv_q2';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_kttv_q3', 'Câu 03: Thế nào là triều hỗn hợp?', 'gk2_kttv', 3);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q3_a1', 'Là hiện tượng trong nửa tháng âm lịch, chu kỳ thuỷ triều thay đổi từ bán nhật triều sang nhật triều', 'gk2_kttv_q3');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q3_a2', 'Là hiện tượng trong nửa tháng âm lịch, chu kỳ thuỷ triều thay đổi từ nhật triều sang bán nhật triều', 'gk2_kttv_q3');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q3_a3', 'Là hiện tượng trong nửa tháng âm lịch, chu kỳ thuỷ triều thay đổi từ bán nhật triều sang nhật triều và ngược lại.', 'gk2_kttv_q3');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q3_a4', 'Là hiện tượng trong nửa tháng âm lịch, chu kỳ thuỷ triều không thay đổi từ nhật triều sang bán nhật triều', 'gk2_kttv_q3');
UPDATE questions SET correct_answer_id = 'gk2_kttv_q3_a3' WHERE id = 'gk2_kttv_q3';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_kttv_q4', 'Câu 04: Ở chu kỳ bán nhật triều thì triều hỗn hợp được gọi là?', 'gk2_kttv', 4);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q4_a1', 'Bán nhật triều đều', 'gk2_kttv_q4');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q4_a2', 'Bán nhật triều không đều', 'gk2_kttv_q4');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q4_a3', 'Nhật triều đều', 'gk2_kttv_q4');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q4_a4', 'Nhật triều không đều', 'gk2_kttv_q4');
UPDATE questions SET correct_answer_id = 'gk2_kttv_q4_a2' WHERE id = 'gk2_kttv_q4';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_kttv_q5', 'Câu 05: Ở chu kỳ nhật triều thì triều hỗn hợp được gọi là?', 'gk2_kttv', 5);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q5_a1', 'Bán nhật triều đều', 'gk2_kttv_q5');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q5_a2', 'Bán nhật triều không đều', 'gk2_kttv_q5');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q5_a3', 'Nhật triều đều', 'gk2_kttv_q5');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q5_a4', 'Nhật triều không đều', 'gk2_kttv_q5');
UPDATE questions SET correct_answer_id = 'gk2_kttv_q5_a4' WHERE id = 'gk2_kttv_q5';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_kttv_q6', 'Câu 06: Thế nào là độ cao thủy triều (H)?', 'gk2_kttv', 6);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q6_a1', 'Là độ cao mực nước tính từ đáy biển đến ki tàu tại thời điểm quan trắ', 'gk2_kttv_q6');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q6_a2', 'Là độ cao mực nước tính từ đáy biển đến mớn nước hiện tại của tàu tại thời điểm quan trắ', 'gk2_kttv_q6');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q6_a3', 'Là độ cao mực nước tính từ đáy biển đến mớn nước trung bình của tàu tại thời điểm quan trắ', 'gk2_kttv_q6');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q6_a4', 'Là độ cao mực nước trên số “0” độ sâu tại thời điểm quan trắC', 'gk2_kttv_q6');
UPDATE questions SET correct_answer_id = 'gk2_kttv_q6_a4' WHERE id = 'gk2_kttv_q6';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_kttv_q7', 'Câu 07: Thế nào là biên độ triều (B)?', 'gk2_kttv', 7);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q7_a1', 'Là khoảng cách thẳng đứng giữa mực nước lớn và đáy biển.', 'gk2_kttv_q7');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q7_a2', 'Là khoảng cách thẳng đứng giữa mực nước ròng và đáy biển.', 'gk2_kttv_q7');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q7_a3', 'Là khoảng cách thẳng đứng giữa mực nước lớn và số 0 độ sâu.', 'gk2_kttv_q7');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q7_a4', 'Là khoảng cách thẳng đứng giữa mực nước lớn và nước ròng kế tiếp.', 'gk2_kttv_q7');
UPDATE questions SET correct_answer_id = 'gk2_kttv_q7_a4' WHERE id = 'gk2_kttv_q7';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_kttv_q8', 'Câu 8: Biên độ thủy triều đạt cao nhất ở chế độ :', 'gk2_kttv', 8);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q8_a1', 'Bán nhật triều.', 'gk2_kttv_q8');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q8_a2', 'Nhật triều.', 'gk2_kttv_q8');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q8_a3', 'Tạp triều.', 'gk2_kttv_q8');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q8_a4', 'Triều hỗn hợp', 'gk2_kttv_q8');
UPDATE questions SET correct_answer_id = 'gk2_kttv_q8_a2' WHERE id = 'gk2_kttv_q8';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_kttv_q9', 'Câu 9: Thuỷ triều là?', 'gk2_kttv', 9);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q9_a1', 'Hiện tượng dao động của mực nước biển và đại dương có chu kỳ, dưới tác động của lực hấp dẫn vũ trụ từ mặt trời.', 'gk2_kttv_q9');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q9_a2', 'Hiện tượng dao động của mực nước biển và đại dương có chu kỳ, dưới tác động của lực hấp dẫn vũ trụ từ mặt trăng.', 'gk2_kttv_q9');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q9_a3', 'Hiện tượng dao động của mực nước biển và đại dương có chu kỳ, dưới tác động của lực hấp dẫn vũ trụ từ mặt trăng và mặt trời.', 'gk2_kttv_q9');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q9_a4', 'Hiện tượng dao động của mực nước biển và đại dương có chu kỳ, dưới tác động của lực hấp dẫn vũ trụ từ các hành tinh trong hệ mặt trời.', 'gk2_kttv_q9');
UPDATE questions SET correct_answer_id = 'gk2_kttv_q9_a3' WHERE id = 'gk2_kttv_q9';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_kttv_q10', 'Câu 10: Nước ta có các chế độ thủy triều nào?', 'gk2_kttv', 10);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q10_a1', 'Nhật triều, bán nhật triều, triều hỗn hợp', 'gk2_kttv_q10');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q10_a2', 'Nhật triều, bán nhật triều', 'gk2_kttv_q10');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q10_a3', 'Bán nhật triều, triều hỗn hợp, triều sóc vọng', 'gk2_kttv_q10');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q10_a4', 'Nhật triều, triều sóc vọng, triều trực thế.', 'gk2_kttv_q10');
UPDATE questions SET correct_answer_id = 'gk2_kttv_q10_a1' WHERE id = 'gk2_kttv_q10';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_kttv_q11', 'Câu 11) Khi có dòng chảy phủ luồng, ta xác định luồng chạy tàu an toàn như thế nào?', 'gk2_kttv', 11);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q11_a1', 'Mặt sông xuất hiện nước cuộn, nhiều ngấn nước, sóng nhấp nhô hoặc sóng ngang, bước sóng ngắn, gợn lăn tăn và có cả những xoáy nước hay bọt nước.', 'gk2_kttv_q11');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q11_a2', 'Mặt sông có dòng chảy mà vệt nước dài liên tục, bề mặt dòng chảy êm, lưu tốc dòng chảy mạnh.', 'gk2_kttv_q11');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q11_a3', 'Mặt sông có dòng chảy lưu tốc chậm, mặt nước sáng, có sóng gợn lăn tăn, tỏa màu lấp lánh hoặc mặt nước xáo động, thỉnh thoảng có sóng cuộn hay có bọt nước, mặt nước không êm thiếu ổn định và không liên tục', 'gk2_kttv_q11');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q11_a4', 'Cả 3 đáp án đều đúng.', 'gk2_kttv_q11');
UPDATE questions SET correct_answer_id = 'gk2_kttv_q11_a2' WHERE id = 'gk2_kttv_q11';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_kttv_q12', 'Câu 12) Dòng chảy vật thường xuất hiện ở khu vực nào ?', 'gk2_kttv', 12);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q12_a1', 'Xuất hiện ở những nơi có mực nước cao, đột ngột đổ xuống thấp rồi lan tỏa ra nhiều hướng hoặc những nơi giữa luồng sông có đá ngầm, bãi ngầm, bãi cát, hòn nổi.', 'gk2_kttv_q12');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q12_a2', 'Xuất hiện ở những nơi sông cong, dòng nước đến chổ bị uốn cong thì tập trung đổ thẳng về phía bờ lõm (bờ vịnh), bị bờ ngăn lại, dòng chảy lại quay hướng xuống đáy và đổ ngang về phía bờ lồi.', 'gk2_kttv_q12');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q12_a3', 'Xuất hiện ở khúc sông thẳng, vào mùa nước lớn, nhất là những ngày có lũ, mực nước sông dâng lên cao đột ngột.', 'gk2_kttv_q12');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q12_a4', 'Xuất hiện ở đoạn sông có bờ lõm vào, do dòng chảy đang đi thẳng gặp phải bờ lõm sẽ bị thay đổi hướng một cách đột ngột tạo nên hiện tượng chảy rối và dần dần đi theo hướng trôn ốc từ trên xuống dưới', 'gk2_kttv_q12');
UPDATE questions SET correct_answer_id = 'gk2_kttv_q12_a2' WHERE id = 'gk2_kttv_q12';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_kttv_q13', 'Câu 13) Nguyên nhân nào hình thành xoáy âm áp?', 'gk2_kttv', 13);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q13_a1', 'Do dòng nước đang đi thẳng gặp bờ lồi hay ghềnh đá, chướng ngại vật ăn nhô ra sông, làm cho dòng chảy thay đổi chiều đột ngột, chảy cuộn tròn theo hình trôn ốc từ dưới lên trên', 'gk2_kttv_q13');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q13_a2', 'Do dòng chảy đang đi thẳng gặp phải bờ lõm sẽ bị thay đổi hướng một cách đột ngột tạo nên hiện tượng chảy rối và dần dần đi theo hướng trôn ốc từ trên xuống dưới, làm cho nước hình thành một vùng có chiều dòng chảy cuộn tròn đi xuống.', 'gk2_kttv_q13');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q13_a3', 'Do dòng nước chảy đến chổ bị uốn cong thì tập trung đổ thẳng về phía bờ lõm (bờ vịnh), bị bờ ngăn lại, dòng chảy lại quay hướng xuống đáy và đổ ngang về phía bờ lồi (bờ doi)', 'gk2_kttv_q13');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q13_a4', 'Tất cả các đáp án trên đều đúng.', 'gk2_kttv_q13');
UPDATE questions SET correct_answer_id = 'gk2_kttv_q13_a2' WHERE id = 'gk2_kttv_q13';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_kttv_q14', 'Câu 14) Nguyên nhân nào hình thành dòng chảy xoáy trục ngang?', 'gk2_kttv', 14);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q14_a1', 'do dòng nước đang đi thẳng gặp bờ lồi hay ghềnh đá, chướng ngại vật ăn nhô ra sông, làm cho dòng chảy thay đổi chiều đột ngột, chảy cuộn tròn theo hình trôn ốc từ dưới lên trên', 'gk2_kttv_q14');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q14_a2', 'Do dòng chảy đang đi thẳng gặp phải bờ lõm sẽ bị thay đổi hướng một cách đột ngột tạo nên hiện tượng chảy rối và dần dần đi theo hướng trôn ốc từ trên xuống dưới, làm cho nước hình thành một vùng có chiều dòng chảy cuộn tròn đi xuống.', 'gk2_kttv_q14');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q14_a3', 'Do dòng chảy đang đi thẳng do gặp đáy sông không bằng phẳng dạng bậc thềm (tam cấp) nên bị mất thăng bằng và đâm thẳng xuống đáy, sau đó mới ngóc lên lại bị dòng nước trên mặt xô tới buộc chúng phải chảy cuộn tròn quanh đường trục nằm ngang.', 'gk2_kttv_q14');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q14_a4', 'Do dòng nước chảy đến chổ bị uốn cong thì tập trung đổ thẳng về phía bờ lõm (bờ vịnh), bị bờ ngăn lại, dòng chảy lại quay hướng xuống đáy và đổ ngang về phía bờ lồi (bờ doi)', 'gk2_kttv_q14');
UPDATE questions SET correct_answer_id = 'gk2_kttv_q14_a3' WHERE id = 'gk2_kttv_q14';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_kttv_q15', 'Câu 15: Khu vực nào thường sinh ra cồn bãi nhiều nhất?', 'gk2_kttv', 15);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q15_a1', 'Thượng lưu.', 'gk2_kttv_q15');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q15_a2', 'Trung lưu.', 'gk2_kttv_q15');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q15_a3', 'Hạ lưu.', 'gk2_kttv_q15');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q15_a4', 'Trung lưu - Hạ lưu.', 'gk2_kttv_q15');
UPDATE questions SET correct_answer_id = 'gk2_kttv_q15_a3' WHERE id = 'gk2_kttv_q15';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_kttv_q16', 'Câu 16: Khu vực thượng lưu thường có đặc điểm gì?', 'gk2_kttv', 16);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q16_a1', 'Độ dốc lớn, lưu tốc lớn và có nhiều bãi cạn.', 'gk2_kttv_q16');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q16_a2', 'Độ dốc lớn, lưu tốc nhỏ và có nhiều ghềnh đá nguy hiểm.', 'gk2_kttv_q16');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q16_a3', 'Độ dốc lớn, lưu tốc lớn , nhiều ghềnh đá nguy hiểm.', 'gk2_kttv_q16');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q16_a4', 'Độ dốc lớn, lưu tốc nhỏ', 'gk2_kttv_q16');
UPDATE questions SET correct_answer_id = 'gk2_kttv_q16_a3' WHERE id = 'gk2_kttv_q16';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_kttv_q17', 'Câu 17: Dạng đoạn sông cong thường có đặc điểm gì?', 'gk2_kttv', 17);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q17_a1', 'Bên bờ vịnh thường có bãi cạn.', 'gk2_kttv_q17');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q17_a2', 'Bên bờ doi thường có bãi cạn.', 'gk2_kttv_q17');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q17_a3', 'Cả hai bên ven bờ thường có bãi cạn.', 'gk2_kttv_q17');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q17_a4', 'Ở giữa sông có bãi cạn', 'gk2_kttv_q17');
UPDATE questions SET correct_answer_id = 'gk2_kttv_q17_a2' WHERE id = 'gk2_kttv_q17';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_kttv_q18', 'Câu 18: Dòng chảy vặn thường xuất hiện khi dòng chảy gặp phải địa hình gì?', 'gk2_kttv', 18);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q18_a1', 'Đoạn sông cong.', 'gk2_kttv_q18');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q18_a2', 'Đoạn sông có dòng chảy phân luồng.', 'gk2_kttv_q18');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q18_a3', 'Đoạn sông có dòng chảy phủ luồng', 'gk2_kttv_q18');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q18_a4', 'Đoạn sông thẳng', 'gk2_kttv_q18');
UPDATE questions SET correct_answer_id = 'gk2_kttv_q18_a1' WHERE id = 'gk2_kttv_q18';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_kttv_q19', 'Câu 19: Dòng chảy phân luồng thường xuất hiện khi nào?', 'gk2_kttv', 19);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q19_a1', 'a. Có cồn ở giữa sông', 'gk2_kttv_q19');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q19_a2', 'b. Có cồn ở bờ phải', 'gk2_kttv_q19');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q19_a3', 'c. Có cồn ở bờ trái', 'gk2_kttv_q19');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q19_a4', 'd. Có cồn ở cả hai bên bờ', 'gk2_kttv_q19');
UPDATE questions SET correct_answer_id = 'gk2_kttv_q19_a1' WHERE id = 'gk2_kttv_q19';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_kttv_q20', 'Câu 20: Dòng nước chảy xoáy thường xuất hiện ở đâu?', 'gk2_kttv', 20);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q20_a1', 'a. Nơi bờ sông bị lở đột ngột, nơi có các công trình ngầm hoặc chướng ngại vật', 'gk2_kttv_q20');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q20_a2', 'b. Nơi sông thẳng', 'gk2_kttv_q20');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q20_a3', 'c. Nơi sông cong đều', 'gk2_kttv_q20');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_kttv_q20_a4', 'd. Nơi cửa sông', 'gk2_kttv_q20');
UPDATE questions SET correct_answer_id = 'gk2_kttv_q20_a1' WHERE id = 'gk2_kttv_q20';