INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q1', 'CÂU HỎI TRẮC NGHIỆM MÔN HÀNG HẢI', 'gk2_hanghai', 1);
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q2', 'Câu 1. Vòng tròn lớn nằm trong mặt phẳng vuông góc với trục trái đất, đi qua tâm trái đất là:', 'gk2_hanghai', 2);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q2_a1', 'Vòng tròn kinh tuyến', 'gk2_hanghai_q2');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q2_a2', 'Vòng tròn xích đạo', 'gk2_hanghai_q2');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q2_a3', 'Vòng tròn vĩ tuyến', 'gk2_hanghai_q2');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q2_a4', 'Vòng tròn kinh tuyến gốc', 'gk2_hanghai_q2');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q2_a2' WHERE id = 'gk2_hanghai_q2';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q3', 'Câu 2. Vòng tròn nhỏ mà mặt phẳng chứa nó song song với mặt phẳng xích đạo là:', 'gk2_hanghai', 3);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q3_a1', 'Vòng tròn vĩ tuyến.', 'gk2_hanghai_q3');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q3_a2', 'Vòng tròn kinh tuyến.', 'gk2_hanghai_q3');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q3_a3', 'Vòng tròn xích đạo.', 'gk2_hanghai_q3');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q3_a4', 'Vòng tròn xích vĩ.', 'gk2_hanghai_q3');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q3_a1' WHERE id = 'gk2_hanghai_q3';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q4', 'Câu 3. Hướng đi thật của tàu là:', 'gk2_hanghai', 4);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q4_a1', 'Góc hợp bởi đường bắc kinh tuyến trái đất đến đường phương vị mục tiêu ngược, tính thuận chiều kim đồng hồ từ 000 đến 3600.', 'gk2_hanghai_q4');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q4_a2', 'Góc hợp bởi đường bắc kinh tuyến trái đất đến đường hướng đi của tàu, tính thuận chiều kim đồng hồ từ 000 đến 3600.', 'gk2_hanghai_q4');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q4_a3', 'Góc hợp bởi đường bắc kinh tuyến trái đất đến đường phương vị mục tiêu, tính thuận chiều kim đồng hồ từ 000 đến 3600.', 'gk2_hanghai_q4');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q4_a4', 'Góc hợp bởi đường mũi lái tàu và đường phương vị mục tiêu, tính thuận chiều kim đồng hồ từ 000 đến 3600.', 'gk2_hanghai_q4');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q4_a2' WHERE id = 'gk2_hanghai_q4';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q5', 'Câu 4. Phương vị thật của mục tiêu là:', 'gk2_hanghai', 5);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q5_a1', 'Góc hợp bởi đường bắc kinh tuyến trái đất đến đường phương vị mục tiêu ngược, tính thuận chiều kim đồng hồ từ 000 đến 3600.', 'gk2_hanghai_q5');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q5_a2', 'Góc hợp bởi đường bắc kinh tuyến trái đất đến đường phương vị mục tiêu, tính thuận chiều kim đồng hồ từ 000 đến 3600.', 'gk2_hanghai_q5');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q5_a3', 'Góc hợp bởi đường bắc kinh tuyến trái đất đến đường hướng đi của tàu, tính thuận chiều kim đồng hồ từ 000 đến 3600.', 'gk2_hanghai_q5');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q5_a4', 'Góc hợp bởi đường mũi lái tàu và đường phương vị mục tiêu, tính thuận chiều kim đồng hồ từ 000 đến 3600.', 'gk2_hanghai_q5');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q5_a2' WHERE id = 'gk2_hanghai_q5';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q6', 'Câu 5. Góc mạn là:', 'gk2_hanghai', 6);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q6_a1', 'Góc hợp bởi đường bắc kinh tuyến trái đất đến đường phương vị mục tiêu ngược, tính thuận chiều kim đồng hồ từ 000 đến 1800.', 'gk2_hanghai_q6');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q6_a2', 'Góc hợp bởi đường mũi lái tàu và đường phương vị mục tiêu, tính từ mũi tàu sang phải hoặc sang trái từ 000 đến 1800.', 'gk2_hanghai_q6');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q6_a3', 'Góc hợp bởi đường bắc kinh tuyến trái đất đến đường hướng đi của tàu, tính thuận chiều kim đồng hồ từ 000 đến 1800.', 'gk2_hanghai_q6');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q6_a4', 'Góc hợp bởi đường bắc kinh tuyến trái đất đến đường phương vị mục tiêu, tính thuận chiều kim đồng hồ từ 000 đến 1800.', 'gk2_hanghai_q6');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q6_a2' WHERE id = 'gk2_hanghai_q6';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q7', 'Câu 6. Độ lệch địa từ là:', 'gk2_hanghai', 7);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q7_a1', 'Góc hợp bởi bắc kinh tuyến trái đất với đường bắc kinh tuyến từ tại một điểm.', 'gk2_hanghai_q7');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q7_a2', 'Góc hợp bởi bắc kinh tuyến trái đất với đường hướng đi của tàu tại một điểm.', 'gk2_hanghai_q7');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q7_a3', 'Góc hợp bởi bắc kinh tuyến trái đất với đường phương vị mục tiêu tại một điểm.', 'gk2_hanghai_q7');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q7_a4', 'Góc hợp bởi đường kinh tuyến trái đất đường phương vị mục tiêu ngược tại một điểm.', 'gk2_hanghai_q7');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q7_a1' WHERE id = 'gk2_hanghai_q7';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q8', 'Câu 7. Hướng đi địa từ của tàu là:', 'gk2_hanghai', 8);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q8_a1', 'Góc hợp bởi đường bắc kinh tuyến từ đến đường phương vị mục tiêu ngược, tính thuận chiều kim đồng hồ từ 000 đến 3600.', 'gk2_hanghai_q8');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q8_a2', 'Góc hợp bởi đường bắc kinh tuyến từ đến đường hướng đi của tàu, tính thuận chiều kim đồng hồ từ 000 đến 3600.', 'gk2_hanghai_q8');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q8_a3', 'Góc hợp bởi đường bắc kinh tuyến từ đến đường phương vị mục tiêu, tính thuận chiều kim đồng hồ từ 000 đến 3600.', 'gk2_hanghai_q8');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q8_a4', 'Góc hợp bởi đường mũi lái tàu và đường phương vị mục tiêu, tính thuận chiều kim đồng hồ từ 000 đến 3600.', 'gk2_hanghai_q8');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q8_a3' WHERE id = 'gk2_hanghai_q8';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q9', 'Câu 8. Phương vị địa từ của mục tiêu là:', 'gk2_hanghai', 9);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q9_a1', 'Góc hợp bởi đường bắc kinh tuyến từ đến đường phương vị mục tiêu, tính thuận chiều kim đồng hồ từ 000 đến 3600.', 'gk2_hanghai_q9');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q9_a2', 'Góc hợp bởi đường bắc kinh tuyến từ đến đường phương vị mục tiêu ngược, tính thuận chiều kim đồng hồ từ 000 đến 3600.', 'gk2_hanghai_q9');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q9_a3', 'Góc hợp bởi đường bắc kinh tuyến từ đến đường hướng đi của tàu, tính thuận chiều kim đồng hồ từ 000 đến 3600.', 'gk2_hanghai_q9');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q9_a4', 'Góc hợp bởi đường mũi lái tàu và đường phương vị mục tiêu, tính thuận chiều kim đồng hồ từ 000 đến 3600.', 'gk2_hanghai_q9');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q9_a1' WHERE id = 'gk2_hanghai_q9';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q10', 'Câu 9. Hướng đi la bàn của tàu là:', 'gk2_hanghai', 10);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q10_a1', 'Góc hợp bởi đường bắc kinh tuyến la bàn từ đến đường phương vị mục tiêu ngược, tính thuận chiều kim đồng hồ từ 000 đến 3600.', 'gk2_hanghai_q10');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q10_a2', 'Góc hợp bởi đường bắc kinh tuyến la bàn từ đến đường hướng đi của tàu, tính thuận chiều kim đồng hồ từ 000 đến 3600.', 'gk2_hanghai_q10');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q10_a3', 'Góc hợp bởi đường bắc kinh tuyến la bàn từ đến đường phương vị mục tiêu, tính thuận chiều kim đồng hồ từ 000 đến 3600.', 'gk2_hanghai_q10');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q10_a4', 'Góc hợp bởi đường mũi lái tàu và đường phương vị mục tiêu, tính thuận chiều kim đồng hồ từ 000 đến 3600.', 'gk2_hanghai_q10');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q10_a2' WHERE id = 'gk2_hanghai_q10';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q11', 'Câu 10. Phương vị la bàn của mục tiêu là:', 'gk2_hanghai', 11);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q11_a1', 'Góc hợp bởi đường bắc kinh tuyến la bàn từ đến đường phương vị mục tiêu, tính thuận chiều kim đồng hồ từ 000 đến 3600.', 'gk2_hanghai_q11');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q11_a2', 'Góc hợp bởi đường bắc kinh tuyến la bàn từ đến đường phương vị mục tiêu ngược, tính thuận chiều kim đồng hồ từ 000 đến 3600.', 'gk2_hanghai_q11');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q11_a3', 'Góc hợp bởi đường bắc kinh tuyến la bàn từ đến đường hướng đi của tàu, tính thuận chiều kim đồng hồ từ 000 đến 3600.', 'gk2_hanghai_q11');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q11_a4', 'Góc hợp bởi đường mũi lái tàu và đường phương vị mục tiêu, tính thuận chiều kim đồng hồ từ 000 đến 3600.', 'gk2_hanghai_q11');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q11_a1' WHERE id = 'gk2_hanghai_q11';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q12', 'Câu 11. Sai số riêng la bàn từ là:', 'gk2_hanghai', 12);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q12_a1', 'Góc hợp bởi bắc kinh tuyến từ với đường bắc kinh tuyến la bàn tại một điểm.', 'gk2_hanghai_q12');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q12_a2', 'Góc hợp bởi bắc kinh tuyến từ với đường hướng đi của tàu tại một điểm.', 'gk2_hanghai_q12');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q12_a3', 'Góc hợp bởi bắc kinh tuyến từ với đường phương vị mục tiêu tại một điểm.', 'gk2_hanghai_q12');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q12_a4', 'Góc hợp bởi đường kinh từ đất đường phương vị mục tiêu ngược tại một điểm.', 'gk2_hanghai_q12');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q12_a1' WHERE id = 'gk2_hanghai_q12';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q13', 'Câu 14. Kinh tuyến gốc là kinh tuyến đi qua:', 'gk2_hanghai', 13);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q13_a1', 'Nước Anh.', 'gk2_hanghai_q13');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q13_a2', 'Nước Hà Lan.', 'gk2_hanghai_q13');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q13_a3', 'Nước Pháp.', 'gk2_hanghai_q13');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q13_a4', 'Nước Đức.', 'gk2_hanghai_q13');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q13_a1' WHERE id = 'gk2_hanghai_q13';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q14', 'Câu 15. Một hải lý ở vĩ độ 450 có chiều dài là:', 'gk2_hanghai', 14);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q14_a1', '1862.3 mét', 'gk2_hanghai_q14');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q14_a2', '1852,3 mét', 'gk2_hanghai_q14');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q14_a3', '1842,3 mét', 'gk2_hanghai_q14');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q14_a4', '1832,3 mét', 'gk2_hanghai_q14');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q14_a2' WHERE id = 'gk2_hanghai_q14';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q15', 'Câu 17. Số 0 hải đồ được tính từ đáy sông, biển đến:', 'gk2_hanghai', 15);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q15_a1', 'Mực nước thuỷ triều cao nhất.', 'gk2_hanghai_q15');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q15_a2', 'Mực nước thuỷ triều thấp nhất.', 'gk2_hanghai_q15');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q15_a3', 'Mực nước thuỷ triều trung bình.', 'gk2_hanghai_q15');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q15_a4', 'Mực nước tại thời điểm tàu đang hành trình.', 'gk2_hanghai_q15');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q15_a2' WHERE id = 'gk2_hanghai_q15';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q16', 'Câu 18. Trái đất có bán kính là:', 'gk2_hanghai', 16);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q16_a1', 'R = 6.361.110 mét.', 'gk2_hanghai_q16');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q16_a2', 'R = 6.371.110 mét.', 'gk2_hanghai_q16');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q16_a3', 'R= 6.381.110 mét.', 'gk2_hanghai_q16');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q16_a4', 'R= 6.391.110 mét.', 'gk2_hanghai_q16');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q16_a2' WHERE id = 'gk2_hanghai_q16';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q17', 'Câu 19. Trên hải đồ Việt Nam, có chỗ ghi 15 có ý nghĩa:', 'gk2_hanghai', 17);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q17_a1', 'Số 0 hải đồ tại vị trí đó = 15 m.', 'gk2_hanghai_q17');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q17_a2', 'Số 0 hải đồ tại vị trí đó = 1,5m.', 'gk2_hanghai_q17');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q17_a3', 'Độ sâu mực nước tại thời điểm tàu đang hành trình = 1,5m.', 'gk2_hanghai_q17');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q17_a4', 'Độ sâu mực nước khi thuỷ triều lên cao nhất = 15m.', 'gk2_hanghai_q17');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q17_a2' WHERE id = 'gk2_hanghai_q17';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q18', 'Câu 20. Vĩ độ của một điểm trên bề mặt trái đất được xác định bởi:', 'gk2_hanghai', 18);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q18_a1', 'Số đo cung kinh tuyến chắn giữa vĩ tuyến 3000 và vĩ tuyến đi qua điểm ấy.', 'gk2_hanghai_q18');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q18_a2', 'Số đo cung kinh tuyến chắn giữa vĩ tuyến 2000 và vĩ tuyến đi qua điểm ấy.', 'gk2_hanghai_q18');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q18_a3', 'Số đo cung kinh tuyến chắn giữa vĩ tuyến 1000 và vĩ tuyến đi qua điểm ấy.', 'gk2_hanghai_q18');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q18_a4', 'Số đo cung kinh tuyến chắn giữa vĩ tuyến 000(xích đạo) và vĩ tuyến đi qua điểm ấy.', 'gk2_hanghai_q18');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q18_a4' WHERE id = 'gk2_hanghai_q18';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q19', 'Câu 21. Bán kính trái đất có chiều dài là:', 'gk2_hanghai', 19);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q19_a1', 'R = 3436,8 hải lý.', 'gk2_hanghai_q19');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q19_a2', 'R= 3437,8 hải lý.', 'gk2_hanghai_q19');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q19_a3', 'R= 3438,8 hải lý.', 'gk2_hanghai_q19');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q19_a4', 'R= 3439,8 hải lý.', 'gk2_hanghai_q19');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q19_a2' WHERE id = 'gk2_hanghai_q19';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q20', 'Câu 22. Kinh độ của một điểm trên bề mặt trái đất được xác định bởi:', 'gk2_hanghai', 20);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q20_a1', 'Số đo cung vĩ tuyến chắn giữa kinh tuyến 0000(kinh tuyến gốc) và kinh tuyến đi qua điểm ấy.', 'gk2_hanghai_q20');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q20_a2', 'Số đo cung vĩ tuyến chắn giữa kinh tuyến 6000 và kinh tuyến đi qua điểm ấy.', 'gk2_hanghai_q20');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q20_a3', 'Số đo cung vĩ tuyến chắn giữa kinh tuyến 12000và kinh tuyến đi qua điểm ấy.', 'gk2_hanghai_q20');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q20_a4', 'Số đo cung vĩ tuyến chắn giữa kinh tuyến 18000 và kinh tuyến đi qua điểm ấy.', 'gk2_hanghai_q20');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q20_a1' WHERE id = 'gk2_hanghai_q20';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q21', 'Câu 23. Hiệu vĩ độ của hai điểm trên bề mặt trái đất được xác định bởi:', 'gk2_hanghai', 21);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q21_a1', 'Số đo cung kinh tuyến chắn giữa vĩ tuyến 300 và vĩ tuyến thứ 2 đi qua điểm ấy.', 'gk2_hanghai_q21');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q21_a2', 'Số đo cung kinh tuyến chắn giữa vĩ tuyến 1800 và vĩ tuyến thứ 2 đi qua điểm ấy.', 'gk2_hanghai_q21');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q21_a3', 'Số đo cung kinh tuyến chắn giữa vĩ tuyến 000 và vĩ tuyến thứ 2 đi qua điểm ấy.', 'gk2_hanghai_q21');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q21_a4', 'Số đo cung kinh tuyến chắn giữa hai vĩ tuyến đi qua hai điểm ấy đi qua điểm ấy.', 'gk2_hanghai_q21');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q21_a4' WHERE id = 'gk2_hanghai_q21';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q22', 'Câu 24. Hiệu kinh độ của hai điểm trên bề mặt trái đất được xác định bởi:', 'gk2_hanghai', 22);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q22_a1', 'Số đo cung vĩ tuyến chắn giữa hai kinh tuyến đi qua hai điểm ấy.', 'gk2_hanghai_q22');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q22_a2', 'Số đo cung vĩ tuyến chắn giữa kinh tuyến 0000 và kinh tuyến thứ 2 đi qua điểm ấy.', 'gk2_hanghai_q22');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q22_a3', 'Số đo cung vĩ tuyến chắn giữa kinh tuyến 12000 và kinh tuyến thứ 2 đi qua điểm ấy.', 'gk2_hanghai_q22');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q22_a4', 'Số đo cung vĩ tuyến chắn giữa kinh tuyến 18000 và kinh tuyến thứ 2 đi qua điểm ấy.', 'gk2_hanghai_q22');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q22_a1' WHERE id = 'gk2_hanghai_q22';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q23', 'Câu 25. Sai số la bàn là:', 'gk2_hanghai', 23);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q23_a1', 'Góc hợp bởi bắc kinh tuyến trái đất với đường bắc kinh tuyến la bàn tại một điểm.', 'gk2_hanghai_q23');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q23_a2', 'Góc hợp bởi bắc kinh tuyến trái đất với đường hướng đi của tàu tại một điểm.', 'gk2_hanghai_q23');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q23_a3', 'Góc hợp bởi bắc kinh tuyến trái đất với đường phương vị mục tiêu tại một điểm.', 'gk2_hanghai_q23');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q23_a4', 'Góc hợp bởi đường kinh trái đất với đường phương vị mục tiêu ngược tại một điểm.', 'gk2_hanghai_q23');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q23_a1' WHERE id = 'gk2_hanghai_q23';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q24', 'Câu 26. Kinh tuyến người quan sát là:', 'gk2_hanghai', 24);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q24_a1', 'Kinh tuyến 18000.', 'gk2_hanghai_q24');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q24_a2', 'Kinh tuyến đi 12000.', 'gk2_hanghai_q24');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q24_a3', 'Kinh tuyến đi qua Vị trí người quan sát.', 'gk2_hanghai_q24');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q24_a4', 'Kinh tuyến gốc 0000', 'gk2_hanghai_q24');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q24_a3' WHERE id = 'gk2_hanghai_q24';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q25', 'Câu 27. Một liên có chiều dài là:', 'gk2_hanghai', 25);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q25_a1', '187,23 mét', 'gk2_hanghai_q25');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q25_a2', '186,23 mét', 'gk2_hanghai_q25');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q25_a3', '185,23 mét', 'gk2_hanghai_q25');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q25_a4', '184,23 mét', 'gk2_hanghai_q25');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q25_a3' WHERE id = 'gk2_hanghai_q25';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q26', 'Câu 28. Một hải lý có chiều dài là bằng bao nhiêu liên:', 'gk2_hanghai', 26);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q26_a1', '6 liên', 'gk2_hanghai_q26');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q26_a2', '8 liên', 'gk2_hanghai_q26');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q26_a3', '10 liên', 'gk2_hanghai_q26');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q26_a4', '12 liên', 'gk2_hanghai_q26');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q26_a3' WHERE id = 'gk2_hanghai_q26';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q27', 'Câu 29. Một mét có chiều dài là:', 'gk2_hanghai', 27);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q27_a1', '1: 10.000.000 của 1/4vòng kinh tuyến trái đất', 'gk2_hanghai_q27');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q27_a2', '1: 9.000.000 của 1/4vòng kinh tuyến trái đất', 'gk2_hanghai_q27');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q27_a3', '1: 8.000.000 của 1/4vòng kinh tuyến trái đất', 'gk2_hanghai_q27');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q27_a4', '1: 7.000.000 của 1/4vòng kinh tuyến trái đất', 'gk2_hanghai_q27');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q27_a1' WHERE id = 'gk2_hanghai_q27';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q28', 'Câu 30. Đơn vị đo vận tốc Hải lý/giờ (Nơ, Gút) thường dùng để chỉ:', 'gk2_hanghai', 28);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q28_a1', 'Tốc độ ô tô.', 'gk2_hanghai_q28');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q28_a2', 'Tốc độ máy bay.', 'gk2_hanghai_q28');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q28_a3', 'Tốc độ tàu hỏa.', 'gk2_hanghai_q28');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q28_a4', 'Tốc độ tàu thủy.', 'gk2_hanghai_q28');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q28_a4' WHERE id = 'gk2_hanghai_q28';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q29', 'Câu 31. Đơn vị đo vận tốc Liên/phút thường dùng để chỉ:', 'gk2_hanghai', 29);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q29_a1', 'Tốc độ của nước, gió.', 'gk2_hanghai_q29');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q29_a2', 'Tốc độ máy bay.', 'gk2_hanghai_q29');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q29_a3', 'Tốc độ tàu hỏa.', 'gk2_hanghai_q29');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q29_a4', 'Tốc độ tàu thủy.', 'gk2_hanghai_q29');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q29_a4' WHERE id = 'gk2_hanghai_q29';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q30', 'Câu 32. Đơn vị đo vận tốc Mét/giây thường dùng để chỉ:', 'gk2_hanghai', 30);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q30_a1', 'Tốc độ của nước, gió.', 'gk2_hanghai_q30');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q30_a2', 'Tốc độ máy bay.', 'gk2_hanghai_q30');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q30_a3', 'Tốc độ tàu hỏa.', 'gk2_hanghai_q30');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q30_a4', 'Tốc độ tàu thủy.', 'gk2_hanghai_q30');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q30_a4' WHERE id = 'gk2_hanghai_q30';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q31', 'Câu 33. Trái đất quay một vòng thì:', 'gk2_hanghai', 31);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q31_a1', 'Đồng hồ quay được 12 giờ.', 'gk2_hanghai_q31');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q31_a2', 'Đồng hồ quay được 18 giờ.', 'gk2_hanghai_q31');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q31_a3', 'Đồng hồ quay được 24 giờ.', 'gk2_hanghai_q31');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q31_a4', 'Đồng hồ quay được 30 giờ.', 'gk2_hanghai_q31');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q31_a3' WHERE id = 'gk2_hanghai_q31';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q32', 'Câu 34. Trái đất quay 150:', 'gk2_hanghai', 32);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q32_a1', 'Đồng hồ quay được 1 giờ.', 'gk2_hanghai_q32');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q32_a2', 'Đồng hồ quay được 2 giờ.', 'gk2_hanghai_q32');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q32_a3', 'Đồng hồ quay được 3 giờ.', 'gk2_hanghai_q32');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q32_a4', 'Đồng hồ quay được 4 giờ.', 'gk2_hanghai_q32');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q32_a1' WHERE id = 'gk2_hanghai_q32';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q33', 'Câu 35. Một múi giờ cách nhau:', 'gk2_hanghai', 33);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q33_a1', '100 kinh tuyến', 'gk2_hanghai_q33');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q33_a2', '150 kinh tuyến', 'gk2_hanghai_q33');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q33_a3', '200 kinh tuyến', 'gk2_hanghai_q33');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q33_a4', '250 kinh tuyến', 'gk2_hanghai_q33');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q33_a2' WHERE id = 'gk2_hanghai_q33';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q34', 'Câu 36. Trái đất tự quay quanh mình nó theo chiều:', 'gk2_hanghai', 34);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q34_a1', 'Từ Tây sang Đông', 'gk2_hanghai_q34');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q34_a2', 'Từ Đông sang Tây', 'gk2_hanghai_q34');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q34_a3', 'Từ Bắc xuống Nam', 'gk2_hanghai_q34');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q34_a4', 'Từ Nam lên Bắc', 'gk2_hanghai_q34');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q34_a1' WHERE id = 'gk2_hanghai_q34';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q35', 'Câu 37. Đơn vị đo độ sâu của nước trên hải đồ Việt Nam đơn vị tính là:', 'gk2_hanghai', 35);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q35_a1', 'Feet', 'gk2_hanghai_q35');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q35_a2', 'Inches', 'gk2_hanghai_q35');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q35_a3', 'decimet', 'gk2_hanghai_q35');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q35_a4', 'Mét', 'gk2_hanghai_q35');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q35_a4' WHERE id = 'gk2_hanghai_q35';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q36', 'Câu 38. Đơn vị đo độ cao của tháp đèn, đèn biển trên hải đồ Việt Nam đơn vị tính là:', 'gk2_hanghai', 36);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q36_a1', 'decimet', 'gk2_hanghai_q36');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q36_a2', 'Mét', 'gk2_hanghai_q36');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q36_a3', 'Inches', 'gk2_hanghai_q36');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q36_a4', 'Feet', 'gk2_hanghai_q36');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q36_a2' WHERE id = 'gk2_hanghai_q36';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q37', 'Câu 39. Đơn vị đo độ cao của đảo, núi trên hải đồ Việt Nam đơn vị tính là:', 'gk2_hanghai', 37);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q37_a1', 'Mét', 'gk2_hanghai_q37');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q37_a2', 'Ki lô mét', 'gk2_hanghai_q37');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q37_a3', 'Liên', 'gk2_hanghai_q37');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q37_a4', 'Hải lý', 'gk2_hanghai_q37');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q37_a1' WHERE id = 'gk2_hanghai_q37';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q38', 'Câu 40. Trên hải đồ Việt Nam, độ sâu ghi 12 có ý nghĩa:', 'gk2_hanghai', 38);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q38_a1', 'Số 0 hải đồ tại vị trí đó = 12 m.', 'gk2_hanghai_q38');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q38_a2', 'Số 0 hải đồ tại vị trí đó = 1,2m.', 'gk2_hanghai_q38');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q38_a3', 'Độ sâu mực nước tại thời điểm tàu đang hành trình = 1,2m.', 'gk2_hanghai_q38');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q38_a4', 'Độ sâu mực nước khi thuỷ triều lên cao nhất = 12m.', 'gk2_hanghai_q38');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q38_a1' WHERE id = 'gk2_hanghai_q38';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q39', 'Câu 41. Trên hải đồ Việt Nam ký hiệu .. .. .. .. .. chỉ đường đẳng sâu nào:', 'gk2_hanghai', 39);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q39_a1', 'Đường đẳng sâu 2 mét.', 'gk2_hanghai_q39');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q39_a2', 'Đường đẳng sâu 5 mét.', 'gk2_hanghai_q39');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q39_a3', 'Đường đẳng sâu 10 mét.', 'gk2_hanghai_q39');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q39_a4', 'Đường đẳng sâu 20 mét.', 'gk2_hanghai_q39');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q39_a1' WHERE id = 'gk2_hanghai_q39';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q40', 'Câu 42. Trên hải đồ Việt Nam ký hiệu - - - - - chỉ đường đẳng sâu nào:', 'gk2_hanghai', 40);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q40_a1', 'Đường đẳng sâu 2 mét.', 'gk2_hanghai_q40');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q40_a2', 'Đường đẳng sâu 5 mét.', 'gk2_hanghai_q40');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q40_a3', 'Đường đẳng sâu 10 mét.', 'gk2_hanghai_q40');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q40_a4', 'Đường đẳng sâu 20 mét.', 'gk2_hanghai_q40');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q40_a2' WHERE id = 'gk2_hanghai_q40';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q41', 'Câu 43. Trên hải đồ Việt Nam ký hiệu -. -. -. -. -. chỉ đường đẳng sâu nào:', 'gk2_hanghai', 41);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q41_a1', 'Đường đẳng sâu 2 mét.', 'gk2_hanghai_q41');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q41_a2', 'Đường đẳng sâu 5 mét.', 'gk2_hanghai_q41');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q41_a3', 'Đường đẳng sâu 10 mét.', 'gk2_hanghai_q41');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q41_a4', 'Đường đẳng sâu 20 mét.', 'gk2_hanghai_q41');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q41_a3' WHERE id = 'gk2_hanghai_q41';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q42', 'Câu 44. Trên hải đồ Việt Nam ký hiệu -.. -.. -.. -.. -.. chỉ đường đẳng sâu nào:', 'gk2_hanghai', 42);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q42_a1', 'Đường đẳng sâu 2 mét.', 'gk2_hanghai_q42');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q42_a2', 'Đường đẳng sâu 5 mét.', 'gk2_hanghai_q42');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q42_a3', 'Đường đẳng sâu 10 mét.', 'gk2_hanghai_q42');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q42_a4', 'Đường đẳng sâu 20 mét.', 'gk2_hanghai_q42');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q42_a4' WHERE id = 'gk2_hanghai_q42';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q43', 'Câu 45. Trên hải đồ Việt Nam ký hiệu -… -… -... -… -… chỉ đường đẳng sâu nào:', 'gk2_hanghai', 43);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q43_a1', 'Đường đẳng sâu 30 mét.', 'gk2_hanghai_q43');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q43_a2', 'Đường đẳng sâu 10 mét.', 'gk2_hanghai_q43');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q43_a3', 'Đường đẳng sâu 20 mét.', 'gk2_hanghai_q43');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q43_a4', 'Đường đẳng sâu 2 mét.', 'gk2_hanghai_q43');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q43_a1' WHERE id = 'gk2_hanghai_q43';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q44', 'Câu 46. Trên radar núm chức năng đo khoảng cách tới mục tiêu có ký hiệu là:', 'gk2_hanghai', 44);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q44_a1', 'SELECT/ CANCL.', 'gk2_hanghai_q44');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q44_a2', 'VRM1/ VRM2.', 'gk2_hanghai_q44');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q44_a3', 'EBL1 /EBL2.', 'gk2_hanghai_q44');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q44_a4', 'POWER.', 'gk2_hanghai_q44');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q44_a2' WHERE id = 'gk2_hanghai_q44';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q45', 'Câu 47. Núm chức năng A/C RAIN trên máy radar dùng để:', 'gk2_hanghai', 45);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q45_a1', 'Khử nhiễu mưa.', 'gk2_hanghai_q45');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q45_a2', 'Khử nhiễu biển.', 'gk2_hanghai_q45');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q45_a3', 'Khử nhiễu giao thoa.', 'gk2_hanghai_q45');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q45_a4', 'Điều chỉnh độ sáng màn hình.', 'gk2_hanghai_q45');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q45_a1' WHERE id = 'gk2_hanghai_q45';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q46', 'Câu 48. Núm chức năng của A/C SEA trên máy radar dùng để:', 'gk2_hanghai', 46);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q46_a1', 'Khử nhiễu mưa.', 'gk2_hanghai_q46');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q46_a2', 'Khử nhiễu biển.', 'gk2_hanghai_q46');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q46_a3', 'Khử nhiễu giao thoa.', 'gk2_hanghai_q46');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q46_a4', 'Điều chỉnh độ sáng màn hình.', 'gk2_hanghai_q46');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q46_a2' WHERE id = 'gk2_hanghai_q46';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q47', 'Câu 49. Radar được sử dụng trong hàng hải để:', 'gk2_hanghai', 47);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q47_a1', 'Đo khoảng cách từ tàu tới mục tiêu.', 'gk2_hanghai_q47');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q47_a2', 'Đo phương vị từ tàu tới mục tiêu.', 'gk2_hanghai_q47');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q47_a3', 'Dẫn tàu vào luồng.', 'gk2_hanghai_q47');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q47_a4', 'Tất cả các trường hợp trên.', 'gk2_hanghai_q47');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q47_a4' WHERE id = 'gk2_hanghai_q47';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_hanghai_q48', 'Câu 50. Để đo được phương vị đến mục tiêu thì phải bố trí anten và tia quét sao cho:', 'gk2_hanghai', 48);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q48_a1', 'Anten và tia quét đồng bộ với nhau.', 'gk2_hanghai_q48');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q48_a2', 'Anten và tia quét lệch nhau 900.', 'gk2_hanghai_q48');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q48_a3', 'Anten và tia quét lệch nhau 1800.', 'gk2_hanghai_q48');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_hanghai_q48_a4', 'Anten và tia quét lệch nhau 2700.', 'gk2_hanghai_q48');
UPDATE questions SET correct_answer_id = 'gk2_hanghai_q48_a1' WHERE id = 'gk2_hanghai_q48';