INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ttvt_q1', 'Câu 1. Báo động cấp cứu giữa các tàu bằng máy VHF được trực liên lạc trên kênh:', 'gk2_ttvt', 1);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q1_a1', '14.', 'gk2_ttvt_q1');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q1_a2', '16.', 'gk2_ttvt_q1');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q1_a3', '20.', 'gk2_ttvt_q1');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q1_a4', '70.', 'gk2_ttvt_q1');
UPDATE questions SET correct_answer_id = 'gk2_ttvt_q1_a4' WHERE id = 'gk2_ttvt_q1';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ttvt_q2', 'Câu 2. Thông tin liên lạc trên VHF thường sử dụng kênh:', 'gk2_ttvt', 2);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q2_a1', '14.', 'gk2_ttvt_q2');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q2_a2', '16.', 'gk2_ttvt_q2');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q2_a3', '20.', 'gk2_ttvt_q2');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q2_a4', '69.', 'gk2_ttvt_q2');
UPDATE questions SET correct_answer_id = 'gk2_ttvt_q2_a2' WHERE id = 'gk2_ttvt_q2';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ttvt_q3', 'Câu 3. Bức điện gọi chọn số DSC có thông tin:', 'gk2_ttvt', 3);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q3_a1', 'Tên hay số hiệu ID của đài phát', 'gk2_ttvt_q3');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q3_a2', 'Mức độ ưu tiên của cuộc gọi', 'gk2_ttvt_q3');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q3_a3', 'Đài trạm được gọi', 'gk2_ttvt_q3');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q3_a4', 'Tất cả các đáp án trên', 'gk2_ttvt_q3');
UPDATE questions SET correct_answer_id = 'gk2_ttvt_q3_a4' WHERE id = 'gk2_ttvt_q3';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ttvt_q4', 'Câu 4.Báo động cấp cứu là:', 'gk2_ttvt', 4);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q4_a1', 'Tàu báo đi báo động cấp cứu trực tiếp thông qua các đài duyên hải.', 'gk2_ttvt_q4');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q4_a2', 'Tàu báo đi báo động cấp cứu gián tiếp thông qua các đài duyên hải.', 'gk2_ttvt_q4');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q4_a3', 'Tàu báo đi báo động cấp cứu trực tiếp hoặc gián tiếp thông qua các đài duyên hải.', 'gk2_ttvt_q4');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q4_a4', 'Tàu báo đi báo động cấp cứu tới tàu xung quanh.', 'gk2_ttvt_q4');
UPDATE questions SET correct_answer_id = 'gk2_ttvt_q4_a3' WHERE id = 'gk2_ttvt_q4';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ttvt_q5', 'Câu 5.Thông tin an toàn hàng hải là:', 'gk2_ttvt', 5);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q5_a1', 'Thông báo khí tượng thủy văn.', 'gk2_ttvt_q5');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q5_a2', 'Thông báo hàng hải.', 'gk2_ttvt_q5');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q5_a3', 'Thông tin quan trọng khác cho hàng hải.', 'gk2_ttvt_q5');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q5_a4', 'Tất cả các trường hợp trên.', 'gk2_ttvt_q5');
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ttvt_q6', 'Câu 6. Thông tin an toàn hàng hải sử dụng liên lạc bằng phương thức thoại được bắt đầu bằng việc gọi:', 'gk2_ttvt', 6);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q6_a1', 'MAYDAY (3 lần).', 'gk2_ttvt_q6');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q6_a2', 'SECURITY (3 lần).', 'gk2_ttvt_q6');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q6_a3', 'PANPAN (3 lần).', 'gk2_ttvt_q6');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q6_a4', 'Tất cả các trường hợp trên.', 'gk2_ttvt_q6');
UPDATE questions SET correct_answer_id = 'gk2_ttvt_q6_a2' WHERE id = 'gk2_ttvt_q6';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ttvt_q7', 'Câu 7. Thông tin khẩn cấp sử dụng bằng phương thức thoại bắt đầu bằng việc gọi:', 'gk2_ttvt', 7);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q7_a1', 'MAYDAY (3 lần).', 'gk2_ttvt_q7');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q7_a2', 'PANPAN (3 lần).', 'gk2_ttvt_q7');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q7_a3', 'SECURITY (3 lần).', 'gk2_ttvt_q7');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q7_a4', 'Tất cả các đáp án trên.', 'gk2_ttvt_q7');
UPDATE questions SET correct_answer_id = 'gk2_ttvt_q7_a2' WHERE id = 'gk2_ttvt_q7';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ttvt_q8', 'Câu 8.Thông tin cấp cứu bằng phương thức thoại được bắt đầu bằng việc gọi:', 'gk2_ttvt', 8);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q8_a1', 'PANPAN (3 lần).', 'gk2_ttvt_q8');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q8_a2', 'MAYDAY (3 lần).', 'gk2_ttvt_q8');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q8_a3', 'SECURITY (3 lần).', 'gk2_ttvt_q8');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q8_a4', 'Tất cả các trường hợp trên.', 'gk2_ttvt_q8');
UPDATE questions SET correct_answer_id = 'gk2_ttvt_q8_a2' WHERE id = 'gk2_ttvt_q8';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ttvt_q9', 'Câu 9. Khi 1 đài được gọi trên kênh 16 VHF thì nó sẽ trả lời trên kênh:', 'gk2_ttvt', 9);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q9_a1', '06.', 'gk2_ttvt_q9');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q9_a2', '13.', 'gk2_ttvt_q9');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q9_a3', '16.', 'gk2_ttvt_q9');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q9_a4', '68.', 'gk2_ttvt_q9');
UPDATE questions SET correct_answer_id = 'gk2_ttvt_q9_a3' WHERE id = 'gk2_ttvt_q9';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ttvt_q10', 'Câu 10. Liên lạc gọi chọn số DSC được dùng để:', 'gk2_ttvt', 10);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q10_a1', 'Cho tàu bị nạn phát đi các bức điện cấp cứu.', 'gk2_ttvt_q10');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q10_a2', 'Trạm bờ xác nhận tín hiệu cấp cứu.', 'gk2_ttvt_q10');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q10_a3', 'Trạm bờ phát đi các thông tin khẩn cấp và thông tin an toàn hàng hải.', 'gk2_ttvt_q10');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ttvt_q10_a4', 'Tất cả các trường hợp trên.', 'gk2_ttvt_q10');
UPDATE questions SET correct_answer_id = 'gk2_ttvt_q10_a4' WHERE id = 'gk2_ttvt_q10';