INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ktvt_q1', 'CÂU HỎI MÔN KINH TẾ VẬN TẢI: 20 câu', 'gk2_ktvt', 1);
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ktvt_q2', 'Câu 1: Người kinh doanh vận tải hàng hóa không có nghĩa vụ:', 'gk2_ktvt', 2);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q2_a1', 'a. Cung cấp phương tiện đúng chủng loại, đúng địa điểm, bảo quản hàng hóa trong quá trình vận tải và giao hàng hóa cho người nhận hàng theo thỏa thuận trong hợp đồng.', 'gk2_ktvt_q2');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q2_a2', 'b. Hướng dẫn xếp, dỡ hàng hóa trên phương tiện', 'gk2_ktvt_q2');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q2_a3', 'c. Chuẩn bị đầy đủ giấy tờ hợp pháp về hàng hóa, đóng gói hàng hóa đúng quy cách, ghi ký hiệu, mã hiệu hàng hóa đầy đủ rõ ràng', 'gk2_ktvt_q2');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q2_a4', 'd. Thông báo cho người thuê vận tải biết thời gian phương tiện đến cảng, bến và thời gian phương tiện đã làm xong thủ tục vào cảng, bến.', 'gk2_ktvt_q2');
UPDATE questions SET correct_answer_id = 'gk2_ktvt_q2_a3' WHERE id = 'gk2_ktvt_q2';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ktvt_q3', 'Câu 2: Người thuê vận tải hàng hóa không có nghĩa vụ:', 'gk2_ktvt', 3);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q3_a1', 'a. Cung cấp giấy tờ, tài liệu và các thông tin cần thiết khác về hàng hóa và đảm bảo tính pháp lý của hàng hóa.', 'gk2_ktvt_q3');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q3_a2', 'b. Thanh toán cước phí vận tải và chi phí phát sinh cho người kinh doanh vận tải hàng hoá;', 'gk2_ktvt_q3');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q3_a3', 'c. Cử người áp tải hàng hoá trong quá trình vận tải đối với loại hàng hoá bắt buộc phải có người áp tải.', 'gk2_ktvt_q3');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q3_a4', 'd. Lập giấy vận chuyển theo mẫu quy định.', 'gk2_ktvt_q3');
UPDATE questions SET correct_answer_id = 'gk2_ktvt_q3_a4' WHERE id = 'gk2_ktvt_q3';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ktvt_q4', 'Câu 3: Người thuê vận tải hàng hóa có quyền:', 'gk2_ktvt', 4);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q4_a1', 'a. Từ chối xếp hàng hoá lên phương tiện mà người kinh doanh vận tải đã bố trí nếu phương tiện không phù hợp để vận tải loại hàng hoá đã thoả thuận trong hợp đồng.', 'gk2_ktvt_q4');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q4_a2', 'b. Yêu cầu người kinh doanh vận tải xác nhận số lượng, niêm phong đối với hàng hóa mà mình gửi đi;', 'gk2_ktvt_q4');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q4_a3', 'c. Yêu cầu người kinh doanh vận tải giao hàng hoá đúng địa điểm, thời gian đã thoả thuận trong hợp đồng.', 'gk2_ktvt_q4');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q4_a4', 'd. Cả ba ý trên.', 'gk2_ktvt_q4');
UPDATE questions SET correct_answer_id = 'gk2_ktvt_q4_a4' WHERE id = 'gk2_ktvt_q4';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ktvt_q5', 'Câu 4: Người kinh doanh vận tải hàng hóa có quyền:', 'gk2_ktvt', 5);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q5_a1', 'a. Yêu cầu người thuê vận tải hàng hóa mở bao, kiện để kiểm tra trong trường hợp nghi ngờ về tính xác thực của việc khai báo chủng loại hàng hóa.', 'gk2_ktvt_q5');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q5_a2', 'b. Từ chối vận tải nếu người thuê vận tải không giao hàng hóa theo thỏa thuận trong hợp đồng;', 'gk2_ktvt_q5');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q5_a3', 'c. Yêu cầu trả tiền lưu hàng hóa trên phương tiện do lỗi của người thuê vận tải, người nhận hàng gây ra.', 'gk2_ktvt_q5');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q5_a4', 'd. Cả ba ý trên.', 'gk2_ktvt_q5');
UPDATE questions SET correct_answer_id = 'gk2_ktvt_q5_a4' WHERE id = 'gk2_ktvt_q5';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ktvt_q6', 'Câu 5. Hàng hóa siêu trường, siêu trọng có kích thước, trọng lượng thực tế là:', 'gk2_ktvt', 6);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q6_a1', 'Chiều rộng trên 10 mét hoặc chiều dài trên 30 mét hoặc chiều cao trên 4,5 mét, trọng lượng trên 50 tấn.', 'gk2_ktvt_q6');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q6_a2', 'Chiều rộng trên 10 mét hoặc chiều dài trên 40 mét hoặc chiều cao trên 3,5 mét, trọng lượng trên 50 tấn.', 'gk2_ktvt_q6');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q6_a3', 'Chiều rộng trên 10 mét hoặc chiều dài trên 30 mét hoặc chiều cao trên 3,5 mét, trọng lượng trên 100 tấn.', 'gk2_ktvt_q6');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q6_a4', 'Chiều rộng trên 10 mét hoặc chiều dài trên 40 mét hoặc chiều cao trên 4,5 mét, trọng lượng trên 100 tấn.', 'gk2_ktvt_q6');
UPDATE questions SET correct_answer_id = 'gk2_ktvt_q6_a4' WHERE id = 'gk2_ktvt_q6';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ktvt_q7', 'Câu 6.Khi giao hàng hóa theo nguyên hầm kẹp chì nếu niêm phong, kẹp chì còn nguyên vẹn thì người kinh doanh vận tải:', 'gk2_ktvt', 7);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q7_a1', 'Phải chịu trách nhiệm về hàng hóa.', 'gk2_ktvt_q7');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q7_a2', 'Tùy từng trường hợp mà phải chịu trách nhiệm về hàng hóa.', 'gk2_ktvt_q7');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q7_a3', 'Phải chịu trách nhiệm 50% về hàng hóa.', 'gk2_ktvt_q7');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q7_a4', 'Không phải chịu trách nhiệm về hàng hóa.', 'gk2_ktvt_q7');
UPDATE questions SET correct_answer_id = 'gk2_ktvt_q7_a4' WHERE id = 'gk2_ktvt_q7';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ktvt_q8', 'Câu 7. Cách xác định trọng lượng hàng bằng vạch mớn nước trên vỏ tàu có đặc điểm:', 'gk2_ktvt', 8);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q8_a1', 'Nhanh chóng.', 'gk2_ktvt_q8');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q8_a2', 'Chính xác.', 'gk2_ktvt_q8');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q8_a3', 'Chỉ dùng xác định các loại hàng có khối lượng nhỏ.', 'gk2_ktvt_q8');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q8_a4', 'Dùng để xác định hàng hóa có giá trị cao.', 'gk2_ktvt_q8');
UPDATE questions SET correct_answer_id = 'gk2_ktvt_q8_a1' WHERE id = 'gk2_ktvt_q8';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ktvt_q9', 'Câu 8. Trên đường vận tải nếu phát hiện hàng hóa thông thường không đúng với kê khai của người thuê vận tải thì người kinh doanh vận tải xử lý:', 'gk2_ktvt', 9);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q9_a1', 'Báo cho người thuê vận tải biết và tiếp tục vận tải đến nơi trả hàng.', 'gk2_ktvt_q9');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q9_a2', 'Báo cho người thuê vận tải biết và cho tàu dừng lại.', 'gk2_ktvt_q9');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q9_a3', 'Báo cho người thuê vận tải biết và vận tải quay về nơi nhận hàng.', 'gk2_ktvt_q9');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q9_a4', 'Không báo cho người thuê vận tải biết và tiếp tục vận tải đến nơi trả hàng.', 'gk2_ktvt_q9');
UPDATE questions SET correct_answer_id = 'gk2_ktvt_q9_a1' WHERE id = 'gk2_ktvt_q9';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ktvt_q10', 'Câu 9. Phương tiện vận tải bị trưng dụng do lệnh của cơ quan có thẩm quyền thì thuyền trưởng phải:', 'gk2_ktvt', 10);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q10_a1', 'Thông báo cho người kinh doanh vận tải biết.', 'gk2_ktvt_q10');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q10_a2', 'Thông báo cho người thuê vận tải biết.', 'gk2_ktvt_q10');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q10_a3', 'Không cần phải thông báo cho người kinh doanh vận tải và người thuê vận tải biết.', 'gk2_ktvt_q10');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q10_a4', 'Thông báo cho người kinh doanh vận tải và người thuê vận tải biết để phối hợp thực hiện.', 'gk2_ktvt_q10');
UPDATE questions SET correct_answer_id = 'gk2_ktvt_q10_a4' WHERE id = 'gk2_ktvt_q10';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ktvt_q11', 'Câu 10. Ngành vận tải thủy nội địa có những đặc điểm:', 'gk2_ktvt', 11);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q11_a1', 'Tốc độ vận tải thấp và giá thành vận tải thấp.', 'gk2_ktvt_q11');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q11_a2', 'Tốc độ vận tải cao và giá thành vận tải thấp.', 'gk2_ktvt_q11');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q11_a3', 'Tốc độ vận tải thấp và giá thành vận tải cao.', 'gk2_ktvt_q11');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q11_a4', 'Tốc độ vận tải cao và giá thành vận tải cao.', 'gk2_ktvt_q11');
UPDATE questions SET correct_answer_id = 'gk2_ktvt_q11_a1' WHERE id = 'gk2_ktvt_q11';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ktvt_q12', 'Câu 11. Quá trình sản xuất vận tải thủy nội địa bao gồm những thành phần:', 'gk2_ktvt', 12);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q12_a1', 'Người kinh doanh vận tải và cảng bến phục vụ xếp dỡ hàng hóa.', 'gk2_ktvt_q12');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q12_a2', 'Người thuê vận tải và người kinh doanh vận tải.', 'gk2_ktvt_q12');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q12_a3', 'Người thuê vận tải và cảng bến phục vụ xếp dỡ hàng hóa.', 'gk2_ktvt_q12');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q12_a4', 'Người thuê vận tải, người kinh doanh vận tải và cảng bến phục vụ xếp dỡ hàng hóa.', 'gk2_ktvt_q12');
UPDATE questions SET correct_answer_id = 'gk2_ktvt_q12_a4' WHERE id = 'gk2_ktvt_q12';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ktvt_q13', 'Câu 12. Hàng hóa có những đặc tính cơ bản là:', 'gk2_ktvt', 13);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q13_a1', 'Tính vật lý', 'gk2_ktvt_q13');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q13_a2', 'Tính hóa học.', 'gk2_ktvt_q13');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q13_a3', 'Tính sinh học.', 'gk2_ktvt_q13');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q13_a4', 'Tất cả các đặc tính trên.', 'gk2_ktvt_q13');
UPDATE questions SET correct_answer_id = 'gk2_ktvt_q13_a4' WHERE id = 'gk2_ktvt_q13';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ktvt_q14', 'Câu 13. Khi bảo quản hàng hóa cần phải chú ý những đặc tính:', 'gk2_ktvt', 14);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q14_a1', 'Tính chất hàng hóa.', 'gk2_ktvt_q14');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q14_a2', 'Kích thước hàng hóa.', 'gk2_ktvt_q14');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q14_a3', 'Trọng lượng hàng hóa.', 'gk2_ktvt_q14');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q14_a4', 'Cả ba đặc tính trên.', 'gk2_ktvt_q14');
UPDATE questions SET correct_answer_id = 'gk2_ktvt_q14_a1' WHERE id = 'gk2_ktvt_q14';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ktvt_q15', 'Câu 14. Các biện pháp hạ giá thành vận chuyển:', 'gk2_ktvt', 15);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q15_a1', 'Giảm bớt các khoản chi phí không cần thiết.', 'gk2_ktvt_q15');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q15_a2', 'Tăng lượng luân chuyển hàng hóa.', 'gk2_ktvt_q15');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q15_a3', 'Áp dụng khoa học kỹ thuật vào sản xuất vận tải.', 'gk2_ktvt_q15');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q15_a4', 'Tất cả các biện pháp trên.', 'gk2_ktvt_q15');
UPDATE questions SET correct_answer_id = 'gk2_ktvt_q15_a4' WHERE id = 'gk2_ktvt_q15';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ktvt_q16', 'Câu 15. Giá thành vận tải thủy nội địa càng hạ thể hiện những khả năng nào của doanh nghiệp vận tải:', 'gk2_ktvt', 16);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q16_a1', 'Quá trình sản xuất vận tải của doanh nghiệp hợp lý.', 'gk2_ktvt_q16');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q16_a2', 'Quá trình sản xuất vận tải của doanh nghiệp không hợp lý.', 'gk2_ktvt_q16');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q16_a3', 'Sự đi xuống của doanh nghiệp.', 'gk2_ktvt_q16');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q16_a4', 'Tất cả các ý trên.', 'gk2_ktvt_q16');
UPDATE questions SET correct_answer_id = 'gk2_ktvt_q16_a1' WHERE id = 'gk2_ktvt_q16';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ktvt_q17', 'Câu 16. Giá thành vận chuyển đường thủy nội địa là:', 'gk2_ktvt', 17);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q17_a1', 'Tổng các khoản chi phí cần thiết và hợp lý để làm ra một số lượng sản phẩm là 1TPT.', 'gk2_ktvt_q17');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q17_a2', 'Tổng các khoản chi phí cần thiết và hợp lý để làm ra một số lượng sản phẩm là 1T.km hay 1000 T.km.', 'gk2_ktvt_q17');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q17_a3', 'Tổng lợi nhuận để làm ra một số lượng sản phẩm là 1 tấn hàng.', 'gk2_ktvt_q17');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q17_a4', 'Tất cả đáp án trên.', 'gk2_ktvt_q17');
UPDATE questions SET correct_answer_id = 'gk2_ktvt_q17_a2' WHERE id = 'gk2_ktvt_q17';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ktvt_q18', 'Câu 17. Sự cố thương vụ thường được biểu hiện ở các mặt:', 'gk2_ktvt', 18);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q18_a1', 'Hàng hóa bị hư hỏng, biến chất.', 'gk2_ktvt_q18');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q18_a2', 'Hàng hóa bị hao hụt quá mức quy định.', 'gk2_ktvt_q18');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q18_a3', 'Hàng hóa bị mất mát trong khi vận chuyển.', 'gk2_ktvt_q18');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q18_a4', 'Tất cả các ý trên.', 'gk2_ktvt_q18');
UPDATE questions SET correct_answer_id = 'gk2_ktvt_q18_a4' WHERE id = 'gk2_ktvt_q18';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ktvt_q19', 'Câu 18. Nguyên nhân nào sau đây gây ra sự cố thương vụ là:', 'gk2_ktvt', 19);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q19_a1', 'Giao nhận không chính xác, hàng hóa và giấy tờ không khớp với nhau.', 'gk2_ktvt_q19');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q19_a2', 'Xếp dỡ hàng không đúng kỹ thuật làm rách vỡ, hư hỏng.', 'gk2_ktvt_q19');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q19_a3', 'Phương tiện đưa vận chuyển không chuyên dụng.', 'gk2_ktvt_q19');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q19_a4', 'Tất cả các ý trên.', 'gk2_ktvt_q19');
UPDATE questions SET correct_answer_id = 'gk2_ktvt_q19_a4' WHERE id = 'gk2_ktvt_q19';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ktvt_q20', 'Câu 19. Khi xảy ra sự cố thương vụ, thuyền trưởng sẽ xử lý:', 'gk2_ktvt', 20);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q20_a1', 'Lập biên bản sự cố thương vụ cụ thể ngay tại hiện trường, có kiểm tra chính xác.', 'gk2_ktvt_q20');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q20_a2', 'Trong biên bản phải có xác nhận của các nhân chứng và cơ quan chính quyền địa phương.', 'gk2_ktvt_q20');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q20_a3', 'Phải tìm mọi biện pháp giải quyết, ngăn ngừa sự cố lan rộng và thông báo kịp thời cho chủ hàng biết.', 'gk2_ktvt_q20');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q20_a4', 'Tất cả các ý trên.', 'gk2_ktvt_q20');
UPDATE questions SET correct_answer_id = 'gk2_ktvt_q20_a4' WHERE id = 'gk2_ktvt_q20';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_ktvt_q21', 'Câu 20. Trong quá trình vận chuyển hàng hóa, nếu hàng hóa bị mất mát, hư hỏng thì người kinh doanh vận tải phải bồi thường cho người thuê vận tải trong những trường hợp:', 'gk2_ktvt', 21);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q21_a1', 'Hàng hóa bị hư hỏng, mất mát do lỗi của người kinh doanh vận tải.', 'gk2_ktvt_q21');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q21_a2', 'Hàng hóa bị biến chất, bốc hơi do bản chất của hàng hóa hay do thời tiết.', 'gk2_ktvt_q21');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q21_a3', 'Tai nạn do thiên tai gây ra mà bên vận tải đã chuẩn bị mọi biện pháp đề phòng và đã hết sức chống đỡ nhưng không thể khắc phục được.', 'gk2_ktvt_q21');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_ktvt_q21_a4', 'Tất cả các ý trên.', 'gk2_ktvt_q21');
UPDATE questions SET correct_answer_id = 'gk2_ktvt_q21_a1' WHERE id = 'gk2_ktvt_q21';