INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q1', 'Câu 1. Sông Hồng chảy ra biển Đông ở đâu?', 'gk2_luong', 1);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q1_a1', 'Cửa Ba Lạt.', 'gk2_luong_q1');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q1_a2', 'Cửa Lạch Trường.', 'gk2_luong_q1');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q1_a3', 'Cửa Lạch Giang.', 'gk2_luong_q1');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q1_a4', 'Cửa Đáy.', 'gk2_luong_q1');
UPDATE questions SET correct_answer_id = 'gk2_luong_q1_a1' WHERE id = 'gk2_luong_q1';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q2', 'Câu 2. Sông Đáy chảy ra biển Đông ở đâu?', 'gk2_luong', 2);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q2_a1', 'Cửa Ba Lạt.', 'gk2_luong_q2');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q2_a2', 'Cửa Lạch Trường.', 'gk2_luong_q2');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q2_a3', 'Cửa Lạch Giang.', 'gk2_luong_q2');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q2_a4', 'Cửa Đáy.', 'gk2_luong_q2');
UPDATE questions SET correct_answer_id = 'gk2_luong_q2_a4' WHERE id = 'gk2_luong_q2';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q3', 'Câu 3. Sông Trà Lý chảy ra biển Đông ở đâu?', 'gk2_luong', 3);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q3_a1', 'Cửa Ba Lạt.', 'gk2_luong_q3');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q3_a2', 'Cửa Lạch Trường.', 'gk2_luong_q3');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q3_a3', 'Cửa Trà Lý.', 'gk2_luong_q3');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q3_a4', 'Cửa Đáy.', 'gk2_luong_q3');
UPDATE questions SET correct_answer_id = 'gk2_luong_q3_a3' WHERE id = 'gk2_luong_q3';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q4', 'Câu 4. Sông Thái Bình chảy ra biển Đông ở đâu?', 'gk2_luong', 4);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q4_a1', 'Cửa Thái Bình.', 'gk2_luong_q4');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q4_a2', 'Cửa Lạch Trường.', 'gk2_luong_q4');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q4_a3', 'Cửa Lạch Giang.', 'gk2_luong_q4');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q4_a4', 'Cửa Đáy.', 'gk2_luong_q4');
UPDATE questions SET correct_answer_id = 'gk2_luong_q4_a1' WHERE id = 'gk2_luong_q4';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q5', 'Câu 5. Sông Lam (Trung bộ) thuộc tỉnh nào?', 'gk2_luong', 5);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q5_a1', 'Thanh Hóa.', 'gk2_luong_q5');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q5_a2', 'Nghệ An.', 'gk2_luong_q5');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q5_a3', 'Hà Tĩnh.', 'gk2_luong_q5');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q5_a4', 'Quảng Bình.', 'gk2_luong_q5');
UPDATE questions SET correct_answer_id = 'gk2_luong_q5_a2' WHERE id = 'gk2_luong_q5';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q6', 'Câu 6. Sông Nhật Lệ thuộc tỉnh nào?', 'gk2_luong', 6);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q6_a1', 'Quảng Trị.', 'gk2_luong_q6');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q6_a2', 'Quảng Bình.', 'gk2_luong_q6');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q6_a3', 'Hà Tĩnh.', 'gk2_luong_q6');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q6_a4', 'Huế.', 'gk2_luong_q6');
UPDATE questions SET correct_answer_id = 'gk2_luong_q6_a2' WHERE id = 'gk2_luong_q6';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q7', 'Câu 7. Sông Bến Hải thuộc hệ thống sông kênh nào?', 'gk2_luong', 7);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q7_a1', 'Hệ thống sông, kênh miền Trung.', 'gk2_luong_q7');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q7_a2', 'Hệ thống sông Hồng.', 'gk2_luong_q7');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q7_a3', 'Hệ thống sông Mê Kông.', 'gk2_luong_q7');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q7_a4', 'Hệ thống sông Đồng Nai.', 'gk2_luong_q7');
UPDATE questions SET correct_answer_id = 'gk2_luong_q7_a1' WHERE id = 'gk2_luong_q7';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q8', 'Câu 8. Sông Bến Hải thuộc tỉnh nào?', 'gk2_luong', 8);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q8_a1', 'Quảng Ngãi.', 'gk2_luong_q8');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q8_a2', 'Quảng Nam.', 'gk2_luong_q8');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q8_a3', 'Quảng Trị.', 'gk2_luong_q8');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q8_a4', 'Quảng Bình.', 'gk2_luong_q8');
UPDATE questions SET correct_answer_id = 'gk2_luong_q8_a3' WHERE id = 'gk2_luong_q8';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q9', 'Câu 9. Sông Vàm Cỏ Đông thuộc hê thống sông nào?', 'gk2_luong', 9);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q9_a1', 'Hệ thống sông Thái Bình.', 'gk2_luong_q9');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q9_a2', 'Hệ thống sông Hồng.', 'gk2_luong_q9');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q9_a3', 'Hệ thống sông Mê Kông.', 'gk2_luong_q9');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q9_a4', 'Hệ thống sông Đồng Nai.', 'gk2_luong_q9');
UPDATE questions SET correct_answer_id = 'gk2_luong_q9_a4' WHERE id = 'gk2_luong_q9';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q10', 'Câu 10. Sông Hậu thuộc hệ thống sông nào?', 'gk2_luong', 10);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q10_a1', 'Hệ thống sông Thái Bình.', 'gk2_luong_q10');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q10_a2', 'Hệ thống sông Hồng.', 'gk2_luong_q10');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q10_a3', 'Hệ thống sông Mê Kông.', 'gk2_luong_q10');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q10_a4', 'Hệ thống sông Đồng Nai.', 'gk2_luong_q10');
UPDATE questions SET correct_answer_id = 'gk2_luong_q10_a3' WHERE id = 'gk2_luong_q10';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q11', 'Câu 11. Hệ thống sông Cửu Long đổ ra biển bởi mấy cửa?', 'gk2_luong', 11);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q11_a1', '6 cửa.', 'gk2_luong_q11');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q11_a2', '7 Cửa.', 'gk2_luong_q11');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q11_a3', '8 cửa.', 'gk2_luong_q11');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q11_a4', '9 cửa.', 'gk2_luong_q11');
UPDATE questions SET correct_answer_id = 'gk2_luong_q11_a4' WHERE id = 'gk2_luong_q11';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q12', 'Câu 12. Sông Hồng thuộc hệ thống sông nào?', 'gk2_luong', 12);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q12_a1', 'Hệ thống sông Thái Bình.', 'gk2_luong_q12');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q12_a2', 'Hệ thống sông Hồng.', 'gk2_luong_q12');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q12_a3', 'Hệ thống sông Mê Kông.', 'gk2_luong_q12');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q12_a4', 'Hệ thống sông Đồng Nai.', 'gk2_luong_q12');
UPDATE questions SET correct_answer_id = 'gk2_luong_q12_a2' WHERE id = 'gk2_luong_q12';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q13', 'Câu 13. Sông Cấm thuộc hệ thống sông nào?', 'gk2_luong', 13);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q13_a1', 'Hệ thống sông Thái Bình.', 'gk2_luong_q13');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q13_a2', 'Hệ thống sông Hồng.', 'gk2_luong_q13');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q13_a3', 'Hệ thống sông Mê Kông.', 'gk2_luong_q13');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q13_a4', 'Hệ thống sông Đồng Nai.', 'gk2_luong_q13');
UPDATE questions SET correct_answer_id = 'gk2_luong_q13_a1' WHERE id = 'gk2_luong_q13';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q14', 'Câu 14. Sông Bạch Đằng thuộc hệ thống sông nào?', 'gk2_luong', 14);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q14_a1', 'Hệ thống sông Thái Bình.', 'gk2_luong_q14');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q14_a2', 'Hệ thống sông Hồng.', 'gk2_luong_q14');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q14_a3', 'Hệ thống sông Mê Kông.', 'gk2_luong_q14');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q14_a4', 'Hệ thống sông Đồng Nai.', 'gk2_luong_q14');
UPDATE questions SET correct_answer_id = 'gk2_luong_q14_a1' WHERE id = 'gk2_luong_q14';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q15', 'Câu 16. Đặc điểm của sông ngòi miền Trung là gì?', 'gk2_luong', 15);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q15_a1', 'Sông thường rất ngắn và dốc.', 'gk2_luong_q15');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q15_a2', 'Sông thường rất dài và bằng phẳng.', 'gk2_luong_q15');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q15_a3', 'Sông thường rất dài và dốc.', 'gk2_luong_q15');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q15_a4', 'Tất cả đáp án trên đều đúng.', 'gk2_luong_q15');
UPDATE questions SET correct_answer_id = 'gk2_luong_q15_a1' WHERE id = 'gk2_luong_q15';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q16', 'Câu 17. Sông Bến Hải chảy ra biển Đông ở đâu?', 'gk2_luong', 16);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q16_a1', 'Cửa Ba Lạt.', 'gk2_luong_q16');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q16_a2', 'Cửa Tùng.', 'gk2_luong_q16');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q16_a3', 'Cửa Lạch Giang.', 'gk2_luong_q16');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q16_a4', 'Cửa Đáy.', 'gk2_luong_q16');
UPDATE questions SET correct_answer_id = 'gk2_luong_q16_a2' WHERE id = 'gk2_luong_q16';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q17', 'Câu 18. Sông Hương chảy ra biển Đông ở đâu?', 'gk2_luong', 17);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q17_a1', 'Cửa Ba Lạt.', 'gk2_luong_q17');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q17_a2', 'Cửa Tùng.', 'gk2_luong_q17');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q17_a3', 'Cửa Thuận An.', 'gk2_luong_q17');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q17_a4', 'Cửa Đáy.', 'gk2_luong_q17');
UPDATE questions SET correct_answer_id = 'gk2_luong_q17_a3' WHERE id = 'gk2_luong_q17';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q18', 'Câu 19. Sông Vàm Cỏ Tây thuộc hệ thống sông nào?', 'gk2_luong', 18);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q18_a1', 'Hệ thống sông Thái Bình.', 'gk2_luong_q18');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q18_a2', 'Hệ thống sông Hồng.', 'gk2_luong_q18');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q18_a3', 'Hệ thống sông Mê Kông.', 'gk2_luong_q18');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q18_a4', 'Hệ thống sông Đồng Nai.', 'gk2_luong_q18');
UPDATE questions SET correct_answer_id = 'gk2_luong_q18_a4' WHERE id = 'gk2_luong_q18';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q19', 'Câu 20. Sông Đồng Nai thuộc hệ thống sông nào?', 'gk2_luong', 19);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q19_a1', 'Hệ thống sông Thái Bình.', 'gk2_luong_q19');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q19_a2', 'Hệ thống sông Hồng.', 'gk2_luong_q19');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q19_a3', 'Hệ thống sông Mê Kông.', 'gk2_luong_q19');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q19_a4', 'Hệ thống sông Đồng Nai.', 'gk2_luong_q19');
UPDATE questions SET correct_answer_id = 'gk2_luong_q19_a4' WHERE id = 'gk2_luong_q19';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q20', 'Câu 21. Sông Tiền thuộc hệ thống sông nào?', 'gk2_luong', 20);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q20_a1', 'Hệ thống sông Thái Bình.', 'gk2_luong_q20');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q20_a2', 'Hệ thống sông Hồng.', 'gk2_luong_q20');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q20_a3', 'Hệ thống sông Mê Kông.', 'gk2_luong_q20');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q20_a4', 'Hệ thống sông Đồng Nai.', 'gk2_luong_q20');
UPDATE questions SET correct_answer_id = 'gk2_luong_q20_a4' WHERE id = 'gk2_luong_q20';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q21', 'Câu 22. Sông Tiền đổ ra biển ở mấy cửa?', 'gk2_luong', 21);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q21_a1', '3 cửa.', 'gk2_luong_q21');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q21_a2', '4 cửa.', 'gk2_luong_q21');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q21_a3', '5 cửa.', 'gk2_luong_q21');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q21_a4', '6 cửa.', 'gk2_luong_q21');
UPDATE questions SET correct_answer_id = 'gk2_luong_q21_a4' WHERE id = 'gk2_luong_q21';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q22', 'Câu 23. Sông Hậu đổ ra biển ở mấy cửa?', 'gk2_luong', 22);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q22_a1', '3 cửa.', 'gk2_luong_q22');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q22_a2', '4 cửa.', 'gk2_luong_q22');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q22_a3', '5 cửa.', 'gk2_luong_q22');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q22_a4', '6 cửa.', 'gk2_luong_q22');
UPDATE questions SET correct_answer_id = 'gk2_luong_q22_a1' WHERE id = 'gk2_luong_q22';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q23', 'Câu 23. Sông Hậu đổ ra biển ở mấy cửa?', 'gk2_luong', 23);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q23_a1', '3 cửa.', 'gk2_luong_q23');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q23_a2', '4 cửa.', 'gk2_luong_q23');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q23_a3', '5 cửa.', 'gk2_luong_q23');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q23_a4', '6 cửa.', 'gk2_luong_q23');
UPDATE questions SET correct_answer_id = 'gk2_luong_q23_a1' WHERE id = 'gk2_luong_q23';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q24', 'Câu 24. Sông Bạch Đằng thuộc hệ thống sông nào?', 'gk2_luong', 24);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q24_a1', 'Hệ thống sông Thái Bình.', 'gk2_luong_q24');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q24_a2', 'Hệ thống sông Hồng.', 'gk2_luong_q24');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q24_a3', 'Hệ thống sông Mê Kông.', 'gk2_luong_q24');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q24_a4', 'Hệ thống sông Đồng Nai.', 'gk2_luong_q24');
UPDATE questions SET correct_answer_id = 'gk2_luong_q24_a1' WHERE id = 'gk2_luong_q24';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q25', 'Câu 25. Sông Cầu thuộc hệ thống sông nào?', 'gk2_luong', 25);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q25_a1', 'Hệ thống sông Thái Bình.', 'gk2_luong_q25');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q25_a2', 'Hệ thống sông Hồng.', 'gk2_luong_q25');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q25_a3', 'Hệ thống sông Mê Kông.', 'gk2_luong_q25');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q25_a4', 'Hệ thống sông Đồng Nai.', 'gk2_luong_q25');
UPDATE questions SET correct_answer_id = 'gk2_luong_q25_a1' WHERE id = 'gk2_luong_q25';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q26', 'Câu 26. Sông Đà thuộc hệ thống sông nào?', 'gk2_luong', 26);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q26_a1', 'Hệ thống sông Thái Bình.', 'gk2_luong_q26');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q26_a2', 'Hệ thống sông Hồng.', 'gk2_luong_q26');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q26_a3', 'Hệ thống sông Mê Kông.', 'gk2_luong_q26');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q26_a4', 'Hệ thống sông Đồng Nai.', 'gk2_luong_q26');
UPDATE questions SET correct_answer_id = 'gk2_luong_q26_a2' WHERE id = 'gk2_luong_q26';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q27', 'Câu 26. Sông Đuống thuộc hệ thống sông nào?', 'gk2_luong', 27);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q27_a1', 'Hệ thống sông miền Trung.', 'gk2_luong_q27');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q27_a2', 'Hệ thống sông Hồng.', 'gk2_luong_q27');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q27_a3', 'Hệ thống sông Mê Kông.', 'gk2_luong_q27');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q27_a4', 'Hệ thống sông Đồng Nai.', 'gk2_luong_q27');
UPDATE questions SET correct_answer_id = 'gk2_luong_q27_a2' WHERE id = 'gk2_luong_q27';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q28', 'Câu 27. Sông Thu Bồn chảy ra biển Đông ở đâu?', 'gk2_luong', 28);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q28_a1', 'Cửa Thái Bình.', 'gk2_luong_q28');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q28_a2', 'Cửa Hội An.', 'gk2_luong_q28');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q28_a3', 'Cửa Lạch Giang.', 'gk2_luong_q28');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q28_a4', 'Cửa Đáy.', 'gk2_luong_q28');
UPDATE questions SET correct_answer_id = 'gk2_luong_q28_a2' WHERE id = 'gk2_luong_q28';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q29', 'Câu 28. Sông Hậu chảy ra biển Đông ở đâu?', 'gk2_luong', 29);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q29_a1', 'Cửa Thái Bình.', 'gk2_luong_q29');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q29_a2', 'Cửa Hội An.', 'gk2_luong_q29');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q29_a3', 'Cửa Lạch Giang.', 'gk2_luong_q29');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q29_a4', 'Cửa Định An.', 'gk2_luong_q29');
UPDATE questions SET correct_answer_id = 'gk2_luong_q29_a4' WHERE id = 'gk2_luong_q29';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q30', 'Câu 29. Sông Bạch Đằng chảy ra biển Đông ở đâu?', 'gk2_luong', 30);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q30_a1', 'Cửa Thái Bình.', 'gk2_luong_q30');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q30_a2', 'Cửa Nam Triệu', 'gk2_luong_q30');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q30_a3', 'Cửa Lạch Giang.', 'gk2_luong_q30');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q30_a4', 'Cửa Đáy.', 'gk2_luong_q30');
UPDATE questions SET correct_answer_id = 'gk2_luong_q30_a2' WHERE id = 'gk2_luong_q30';
INSERT INTO questions (id, text, subject_id, display_order) VALUES ('gk2_luong_q31', 'Câu 30. Sông Mã thuộc hệ thống sông nào?', 'gk2_luong', 31);
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q31_a1', 'Hệ thống sông Thái Bình.', 'gk2_luong_q31');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q31_a2', 'Hệ thống sông kênh miền Trung.', 'gk2_luong_q31');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q31_a3', 'Hệ thống sông Mê Kông.', 'gk2_luong_q31');
INSERT INTO answers (id, text, question_id) VALUES ('gk2_luong_q31_a4', 'Hệ thống sông Đồng Nai.', 'gk2_luong_q31');
UPDATE questions SET correct_answer_id = 'gk2_luong_q31_a2' WHERE id = 'gk2_luong_q31';