export type BadgeLevel = 'dong' | 'bac' | 'vang' | 'kim_cuong' | 'role';
export type BadgeGroup = 'on_tap' | 'thi_thu' | 'streak' | 'interaction' | 'special' | 'role';

export interface BadgeDefinition {
  id: string;
  name: string;
  description: string;
  level: BadgeLevel;
  group: BadgeGroup;
  fallbackIcon: string;
  lottieUrl?: string; // URL to Lottie JSON if available
  targetValue?: number; // Target progress value (e.g. 50 questions)
  color: string; // Tailwind color classes for glow/border
  roleId?: string; // Specific role required to unlock (for role badges)
}

export const BADGE_DEFINITIONS: BadgeDefinition[] = [
  // --- NHÓM 1: ÔN TẬP & HỌC TẬP (6 huy hiệu) ---
  {
    id: 'tan_binh_tren_bo',
    name: 'Tân Binh Trên Bờ',
    description: 'Hoàn thành bài ôn tập đầu tiên',
    level: 'dong',
    group: 'on_tap',
    fallbackIcon: '🚢',
    targetValue: 1,
    color: 'from-amber-600 via-amber-500 to-amber-700',
  },
  {
    id: 'thuy_thu_cham_chi',
    name: 'Thủy Thủ Chăm Chỉ',
    description: 'Hoàn thành 50 câu ôn tập',
    level: 'bac',
    group: 'on_tap',
    fallbackIcon: '📖',
    targetValue: 50,
    color: 'from-slate-300 via-slate-100 to-slate-400',
  },
  {
    id: 'hoa_tieu_kien_thuc',
    name: 'Hoa Tiêu Kiến Thức',
    description: 'Hoàn thành 200 câu ôn tập',
    level: 'vang',
    group: 'on_tap',
    fallbackIcon: '🧭',
    targetValue: 200,
    color: 'from-yellow-400 via-amber-300 to-yellow-500',
  },
  {
    id: 'bach_khoa_hang_hai',
    name: 'Bách Khoa Hàng Hải',
    description: 'Hoàn thành ôn tập ở tất cả các môn học',
    level: 'kim_cuong',
    group: 'on_tap',
    fallbackIcon: '📚',
    color: 'from-cyan-300 via-sky-200 to-blue-500',
  },
  {
    id: 'nguoi_khong_ngai_sai',
    name: 'Người Không Ngại Sai',
    description: 'Làm lại 10 câu đã từng sai và trả lời đúng',
    level: 'bac',
    group: 'on_tap',
    fallbackIcon: '💪',
    targetValue: 10,
    color: 'from-slate-300 via-slate-100 to-slate-400',
  },
  {
    id: 'bac_thay_on_luyen',
    name: 'Bậc Thầy Ôn Luyện',
    description: 'Hoàn thành 1000 câu ôn tập (tích lũy)',
    level: 'kim_cuong',
    group: 'on_tap',
    fallbackIcon: '🎯',
    targetValue: 1000,
    color: 'from-cyan-300 via-sky-200 to-blue-500',
  },

  // --- NHÓM 2: THI THỬ & THÀNH TÍCH (5 huy hiệu) ---
  {
    id: 'lan_dau_ra_khoi',
    name: 'Lần Đầu Ra Khơi',
    description: 'Hoàn thành bài thi thử đầu tiên',
    level: 'dong',
    group: 'thi_thu',
    fallbackIcon: '⛵',
    targetValue: 1,
    color: 'from-amber-600 via-amber-500 to-amber-700',
  },
  {
    id: 'vuot_song_thanh_cong',
    name: 'Vượt Sóng Thành Công',
    description: 'Đạt điểm ≥ 70% trong 1 bài thi thử',
    level: 'bac',
    group: 'thi_thu',
    fallbackIcon: '🌊',
    color: 'from-slate-300 via-slate-100 to-slate-400',
  },
  {
    id: 'thuyen_truong_xuat_sac',
    name: 'Thuyền Trưởng Xuất Sắc',
    description: 'Đạt điểm ≥ 90% trong 1 bài thi thử',
    level: 'vang',
    group: 'thi_thu',
    fallbackIcon: '⭐',
    color: 'from-yellow-400 via-amber-300 to-yellow-500',
  },
  {
    id: 'diem_tuyet_doi',
    name: 'Điểm Tuyệt Đối',
    description: 'Đạt 100% điểm trong 1 bài thi thử',
    level: 'kim_cuong',
    group: 'thi_thu',
    fallbackIcon: '💯',
    color: 'from-cyan-300 via-sky-200 to-blue-500',
  },
  {
    id: 'chinh_phuc_bien_ca',
    name: 'Chinh Phục Biển Cả',
    description: 'Hoàn thành 10 bài thi thử (bất kể điểm)',
    level: 'vang',
    group: 'thi_thu',
    fallbackIcon: '🏴‍☠️',
    targetValue: 10,
    color: 'from-yellow-400 via-amber-300 to-yellow-500',
  },

  // --- NHÓM 3: STREAK & KIÊN TRÌ (4 huy hiệu) ---
  {
    id: 'ngon_lua_nho',
    name: 'Ngọn Lửa Nhỏ',
    description: 'Học 3 ngày liên tiếp trên hệ thống',
    level: 'dong',
    group: 'streak',
    fallbackIcon: '🔥',
    targetValue: 3,
    color: 'from-amber-600 via-amber-500 to-amber-700',
  },
  {
    id: 'ngon_hai_dang',
    name: 'Ngọn Hải Đăng',
    description: 'Học 7 ngày liên tiếp trên hệ thống',
    level: 'bac',
    group: 'streak',
    fallbackIcon: '🚨',
    targetValue: 7,
    color: 'from-slate-300 via-slate-100 to-slate-400',
  },
  {
    id: 'thep_da_toi',
    name: 'Thép Đã Tôi',
    description: 'Học 30 ngày liên tiếp trên hệ thống',
    level: 'vang',
    group: 'streak',
    fallbackIcon: '🧱',
    targetValue: 30,
    color: 'from-yellow-400 via-amber-300 to-yellow-500',
  },
  {
    id: 'huyen_thoai_khong_nghi',
    name: 'Huyền Thoại Không Nghỉ',
    description: 'Học 100 ngày liên tiếp trên hệ thống',
    level: 'kim_cuong',
    group: 'streak',
    fallbackIcon: '🏆',
    targetValue: 100,
    color: 'from-cyan-300 via-sky-200 to-blue-500',
  },

  // --- NHÓM 4: CỘNG ĐỒNG & TƯƠNG TÁC (4 huy hiệu) ---
  {
    id: 'nguoi_ban_dong_hanh',
    name: 'Người Bạn Đồng Hành',
    description: 'Tham gia lớp học đầu tiên',
    level: 'dong',
    group: 'interaction',
    fallbackIcon: '🤝',
    targetValue: 1,
    color: 'from-amber-600 via-amber-500 to-amber-700',
  },
  {
    id: 'ngoi_sao_lop_hoc',
    name: 'Ngôi Sao Lớp Học',
    description: 'Đứng Top 3 bảng xếp hạng lớp',
    level: 'vang',
    group: 'interaction',
    fallbackIcon: '✨',
    color: 'from-yellow-400 via-amber-300 to-yellow-500',
  },
  {
    id: 'chien_binh_phong_thi',
    name: 'Chiến Binh Phòng Thi',
    description: 'Tham gia 5 phòng thi trực tuyến',
    level: 'bac',
    group: 'interaction',
    fallbackIcon: '⚔️',
    targetValue: 5,
    color: 'from-slate-300 via-slate-100 to-slate-400',
  },
  {
    id: 'vo_dich_phong_thi',
    name: 'Vô Địch Phòng Thi',
    description: 'Đạt hạng 1 trong 1 phòng thi trực tuyến',
    level: 'vang',
    group: 'interaction',
    fallbackIcon: '👑',
    color: 'from-yellow-400 via-amber-300 to-yellow-500',
  },

  // --- NHÓM 5: ĐẶC BIỆT & ẨN (3 huy hiệu) ---
  {
    id: 'cu_dem_hai_phong',
    name: 'Cú Đêm Hải Phòng',
    description: 'Hoàn thành một bài thi/ôn tập lúc 0h - 5h sáng',
    level: 'bac',
    group: 'special',
    fallbackIcon: '🦉',
    color: 'from-slate-300 via-slate-100 to-slate-400',
  },
  {
    id: 'nguoi_tien_phong',
    name: 'Người Tiên Phong',
    description: 'Là 1 trong 50 người đầu tiên nhận huy hiệu trên hệ thống',
    level: 'vang',
    group: 'special',
    fallbackIcon: '🚀',
    color: 'from-yellow-400 via-amber-300 to-yellow-500',
  },
  {
    id: 'nha_suu_tap',
    name: 'Nhà Sưu Tập',
    description: 'Mở khóa tất cả huy hiệu nhóm Ôn tập, Thi thử và Streak',
    level: 'kim_cuong',
    group: 'special',
    fallbackIcon: '🎒',
    color: 'from-cyan-300 via-sky-200 to-blue-500',
  },

  // --- NHÓM 6: HUY HIỆU ROLE ---
  {
    id: 'role_admin',
    name: 'Quản Trị Viên',
    description: 'Huy hiệu đặc quyền dành cho Admin',
    level: 'role',
    group: 'role',
    fallbackIcon: '👑',
    color: 'from-yellow-400 via-red-500 to-pink-500',
    roleId: 'admin',
  },
  {
    id: 'role_super_admin',
    name: 'Quản Trị Tối Cao',
    description: 'Huy hiệu đặc quyền dành cho Super Admin',
    level: 'role',
    group: 'role',
    fallbackIcon: '👑',
    color: 'from-yellow-400 via-red-500 to-pink-500',
    roleId: 'super_admin',
  },
  {
    id: 'role_lanh_dao',
    name: 'Lãnh Đạo',
    description: 'Huy hiệu đặc quyền dành cho Lãnh Đạo',
    level: 'role',
    group: 'role',
    fallbackIcon: '🦅',
    color: 'from-amber-400 via-orange-500 to-red-600',
    roleId: 'lanh_dao',
  },
  {
    id: 'role_quan_ly',
    name: 'Quản Lý',
    description: 'Huy hiệu đặc quyền dành cho Quản Lý',
    level: 'role',
    group: 'role',
    fallbackIcon: '🛡️',
    color: 'from-blue-400 via-indigo-500 to-sky-600',
    roleId: 'quan_ly',
  },
  {
    id: 'role_giao_vien',
    name: 'Giáo Viên',
    description: 'Huy hiệu đặc quyền dành cho Giáo Viên',
    level: 'role',
    group: 'role',
    fallbackIcon: '👨‍🏫',
    color: 'from-teal-300 via-emerald-400 to-cyan-500',
    roleId: 'giao_vien',
  },
  {
    id: 'role_hoc_vien',
    name: 'Học Viên',
    description: 'Huy hiệu mặc quyền dành cho Học Viên',
    level: 'role',
    group: 'role',
    fallbackIcon: '⚓',
    color: 'from-gray-400 to-slate-500',
    roleId: 'hoc_vien',
  },
];
